import {NextRequest,NextResponse} from "next/server";
import {and,asc,eq,isNull} from "drizzle-orm";
import {getChatGPTUser} from "../../../../chatgpt-auth";
import {getDb} from "../../../../../db";
import {recordAudit,requireTripMember} from "../../../../../db/access";
import {agendaItems} from "../../../../../db/schema";

export async function GET(_:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await getChatGPTUser(),{id}=await params;if(!user)return NextResponse.json({error:"authentication_required"},{status:401});if(!await requireTripMember(id,user.email))return NextResponse.json({error:"forbidden"},{status:403});const db=await getDb();const items=await db.select().from(agendaItems).where(and(eq(agendaItems.tripId,id),isNull(agendaItems.deletedAt))).orderBy(asc(agendaItems.startsAt));return NextResponse.json({items})}
export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await getChatGPTUser(),{id}=await params;if(!user)return NextResponse.json({error:"authentication_required"},{status:401});if(!await requireTripMember(id,user.email,{write:true}))return NextResponse.json({error:"forbidden"},{status:403});const input=await request.json() as {type?:string;title?:string;startsAt?:string;endsAt?:string;timezone?:string;place?:string;address?:string;referenceUrl?:string;notes?:string};if(!input.type||!input.title?.trim()||!input.startsAt)return NextResponse.json({error:"invalid_input"},{status:400});const db=await getDb(),now=new Date().toISOString(),itemId=crypto.randomUUID();const value={id:itemId,tripId:id,type:input.type,title:input.title.trim(),startsAt:input.startsAt,endsAt:input.endsAt,timezone:input.timezone,place:input.place,address:input.address,referenceUrl:input.referenceUrl,notes:input.notes,createdByEmail:user.email,updatedByEmail:user.email,version:1,createdAt:now,updatedAt:now};await db.insert(agendaItems).values(value);await recordAudit({tripId:id,actorEmail:user.email,entityType:"agenda_item",entityId:itemId,action:"create",after:value});return NextResponse.json({id:itemId,version:1,saved:true},{status:201})}
