"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {flightTiming,formatDurationMinutes,formatTimezoneDifference,formatUtcOffset,utcOffsetMinutes} from "./timezone-utils";
type Booking={id:string;ownerEmail:string;kind:"flight"|"stay";title:string;startAt:string;endAt:string;timezone?:string|null;departureTimezone?:string|null;departureUtcAt?:string|null;arrivalTimezone?:string|null;arrivalUtcAt?:string|null;origin?:string|null;destination?:string|null;amountMinor:number;currency:string;bookedAt:string;documentId?:string|null;version:number;canEdit:boolean;attachmentUrl?:string|null};
type BookingOrder={key:string;ownerEmail:string;kind:"flight"|"stay";bookedAt:string;currency:string;amountMinor:number;canEdit:boolean;attachmentUrl?:string|null;legs:Booking[]};
export const groupBookingOrders=(items:Booking[])=>{
 const groups=new Map<string,BookingOrder>();
 for(const booking of items){
  const key=booking.documentId?`document:${booking.documentId}`:`manual:${booking.ownerEmail}:${booking.kind}:${booking.bookedAt}`;
  const existing=groups.get(key);
  if(existing){existing.legs.push(booking);existing.amountMinor+=booking.amountMinor;existing.canEdit=existing.canEdit||booking.canEdit;if(!existing.attachmentUrl&&booking.attachmentUrl)existing.attachmentUrl=booking.attachmentUrl}
  else groups.set(key,{key,ownerEmail:booking.ownerEmail,kind:booking.kind,bookedAt:booking.bookedAt,currency:booking.currency,amountMinor:booking.amountMinor,canEdit:booking.canEdit,attachmentUrl:booking.attachmentUrl,legs:[booking]});
 }
 return [...groups.values()].map(order=>({...order,legs:[...order.legs].sort((a,b)=>a.startAt.localeCompare(b.startAt))})).sort((a,b)=>(a.legs[0]?.startAt??"").localeCompare(b.legs[0]?.startAt??""));
};
const formatBookedAt=(value:string)=>{const date=new Date(value);if(Number.isNaN(date.getTime()))return value.replace("T"," ");return new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Taipei"}).format(date)};
const formatPrice=(order:BookingOrder)=>order.amountMinor>0?`${order.currency} ${(order.amountMinor/100).toLocaleString()}`:"未填";
const legTiming=(leg:Booking)=>{
 if(leg.departureUtcAt&&leg.arrivalUtcAt&&leg.departureTimezone&&leg.arrivalTimezone){const durationMinutes=Math.round((Date.parse(leg.arrivalUtcAt)-Date.parse(leg.departureUtcAt))/60000),departureOffset=utcOffsetMinutes(leg.departureUtcAt,leg.departureTimezone),arrivalOffset=utcOffsetMinutes(leg.arrivalUtcAt,leg.arrivalTimezone);if(durationMinutes>0&&departureOffset!==null&&arrivalOffset!==null)return {durationMinutes,departureOffset,arrivalOffset,difference:arrivalOffset-departureOffset}}
 if(leg.departureTimezone&&leg.arrivalTimezone){const timing=flightTiming({departureLocalAt:leg.startAt,departureTimezone:leg.departureTimezone,arrivalLocalAt:leg.endAt,arrivalTimezone:leg.arrivalTimezone});if(timing)return {durationMinutes:timing.durationMinutes,departureOffset:timing.departureOffsetMinutes,arrivalOffset:timing.arrivalOffsetMinutes,difference:timing.timezoneDifferenceMinutes}}
 return null;
};
export default function BookingPanel({tripId}:{tripId:string}){
 const [items,setItems]=useState<Booking[]>([]),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{if(!tripId)return;const r=await fetch(`/api/trips/${tripId}/bookings`);if(r.ok)setItems((await r.json()).bookings??[])},[tripId]);
 useEffect(()=>{setItems([]);void load();const reload=()=>void load();window.addEventListener("tripclaim:data-changed",reload);return()=>window.removeEventListener("tripclaim:data-changed",reload)},[load]);
 const orders=useMemo(()=>groupBookingOrders(items),[items]);
 const remove=async(order:BookingOrder)=>{const first=order.legs[0];if(!first)return;const label=order.kind==="flight"?`機票・${order.legs.length} 航段`:first.title;if(!window.confirm(`確定永久刪除整張訂單「${label}」？同張訂單的所有去程／回程航段、共同行程、附件與待報支都會刪除，且無法復原。`))return;const r=await fetch(`/api/trips/${tripId}/bookings/${first.id}`,{method:"DELETE"});if(r.ok){const result=await r.json();setNotice(`已永久刪除整張訂單（${result.bookingsDeleted??order.legs.length} 段行程）`);window.dispatchEvent(new Event("tripclaim:data-changed"))}else setNotice("刪除失敗，請重新整理後再試")};
 if(!tripId)return <div className="booking-empty panel">請先建立出差，才能查看班機或住宿。</div>;
 return <details className="shared-booking-details"><summary><span><b>同行者機票／住宿明細</b><small>{orders.length?`${orders.length} 張訂單・需要核對價格或自己的附件時展開`:"尚無訂單・需要時可展開查看"}</small></span><i aria-hidden="true">⌄</i></summary><section className="booking-list"><div className="booking-list-head"><span>次要核對資訊</span><h2>訂單明細</h2><p>共同行程時間以 Calendar 為主；同行者可核對航段、價格與訂購時間，原始附件只限訂單本人查看。</p></div>{notice&&<strong className="booking-notice" role="status">{notice}</strong>}{orders.length===0?<div className="booking-empty panel">還沒有任何訂單。請先從「行前準備 → 我的行前資料」上傳自己的機票或住宿。</div>:orders.map(order=>{const first=order.legs[0],last=order.legs.at(-1);const title=order.kind==="flight"?`機票・${order.legs.length} 航段`:first?.title??"住宿";return <article className="booking-card panel" key={order.key}><header><div><em>{order.kind==="flight"?"✈ 班機":"⌂ 住宿"}</em><b>{title}</b></div><span>{order.ownerEmail}</span></header><dl><div><dt>行程時間</dt><dd>{first?.startAt.replace("T"," ")??"—"}{first?.departureTimezone?` ${first.departureTimezone}`:""} → {last?.endAt.replace("T"," ")??"—"}{last?.arrivalTimezone?` ${last.arrivalTimezone}`:""}</dd></div><div><dt>{order.kind==="flight"?"航段":"地點"}</dt><dd>{order.kind==="flight"?<div className="booking-leg-list">{order.legs.map((leg,index)=>{const timing=legTiming(leg);return <div key={leg.id}><b>{index+1}. {leg.origin||"—"} → {leg.destination||"—"}</b><small>{leg.startAt.replace("T"," ")}{timing?` (${formatUtcOffset(timing.departureOffset)})`:leg.departureTimezone?` (${leg.departureTimezone})`:""} → {leg.endAt.replace("T"," ")}{timing?` (${formatUtcOffset(timing.arrivalOffset)})`:leg.arrivalTimezone?` (${leg.arrivalTimezone})`:""}</small>{timing&&<small>實際飛行 {formatDurationMinutes(timing.durationMinutes)}・{formatTimezoneDifference(timing.difference)}</small>}</div>})}</div>:[first?.origin,first?.destination].filter(Boolean).join(" / ")||"—"}</dd></div><div><dt>整張訂單價格</dt><dd className={`price ${order.amountMinor>0?"":"missing"}`}>{formatPrice(order)}</dd></div><div><dt>訂購時間</dt><dd>{formatBookedAt(order.bookedAt)}</dd></div></dl><footer>{order.canEdit?(order.attachmentUrl?<a href={order.attachmentUrl} target="_blank" rel="noreferrer">查看我的訂單附件</a>:<span>尚無附件</span>):<span>原始附件僅訂單本人可查看</span>}{order.canEdit&&<button className="delete" onClick={()=>remove(order)}>刪除整張訂單</button>}</footer></article>})}</section></details>;
}
