"use client";
import {useEffect,useState} from "react";
type Booking={id:string;ownerEmail:string;kind:"flight"|"stay";title:string;startAt:string;endAt:string;timezone?:string|null;origin?:string|null;destination?:string|null;amountMinor:number;currency:string;bookedAt:string;documentId?:string|null;version:number;canEdit:boolean;attachmentUrl?:string|null};
export default function BookingPanel({tripId}:{tripId:string}){
 const [items,setItems]=useState<Booking[]>([]),[notice,setNotice]=useState("");
 const load=async()=>{if(!tripId)return;const r=await fetch(`/api/trips/${tripId}/bookings`);if(r.ok)setItems((await r.json()).bookings??[])};
 useEffect(()=>{if(!tripId)return;fetch(`/api/trips/${tripId}/bookings`).then(r=>r.ok?r.json():null).then(x=>{if(x)setItems(x.bookings??[])}).catch(()=>null)},[tripId]);
 const remove=async(x:Booking)=>{if(!window.confirm(`確定永久刪除整張訂單「${x.title}」？同張訂單的所有去程／回程航段、共同行程、附件與待報支都會刪除，且無法復原。`))return;const r=await fetch(`/api/trips/${tripId}/bookings/${x.id}`,{method:"DELETE"});if(r.ok){const result=await r.json();setNotice(`已永久刪除整張訂單（${result.bookingsDeleted??1} 段行程）`);window.dispatchEvent(new Event("tripclaim:data-changed"));await load()}else setNotice("刪除失敗，請重新整理後再試")};
 if(!tripId)return <div className="booking-empty panel">請先建立出差，才能查看班機或住宿。</div>;
 return <section className="booking-list"><div className="booking-list-head"><span>所有同行者都看得到</span><h2>訂單時間與價格比較</h2><p>新增或更新請從「我的行前資料」上傳，這裡只顯示已同步的來源訂單。</p></div>{notice&&<strong className="booking-notice">{notice}</strong>}{items.length===0?<div className="booking-empty panel">還沒有任何訂單。請先從「我的行前資料」上傳自己的機票或住宿。</div>:items.map(x=><article className="booking-card panel" key={x.id}><header><div><em>{x.kind==="flight"?"✈ 班機":"⌂ 住宿"}</em><b>{x.title}</b></div><span>{x.ownerEmail}</span></header><dl><div><dt>行程時間</dt><dd>{x.startAt.replace("T"," ")} → {x.endAt.replace("T"," ")}</dd></div><div><dt>路線／地點</dt><dd>{x.origin||"—"} → {x.destination||"—"}</dd></div><div><dt>價格</dt><dd className="price">{x.currency} {(x.amountMinor/100).toLocaleString()}</dd></div><div><dt>訂購時間</dt><dd>{x.bookedAt.replace("T"," ")}</dd></div></dl><footer>{x.attachmentUrl?<a href={x.attachmentUrl} target="_blank" rel="noreferrer">查看訂單附件</a>:<span>尚無附件</span>}{x.canEdit&&<button className="delete" onClick={()=>remove(x)}>刪除</button>}</footer></article>)}</section>;
}
