"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
type Card={id:string;issuer:string;label:string;last4:string};
export default function CardCenter({tripId}:{tripId?:string}){
 const [cards,setCards]=useState<Card[]>([]),[adding,setAdding]=useState(false),[notice,setNotice]=useState("");const file=useRef<HTMLInputElement>(null);
 const load=()=>fetch("/api/cards").then(x=>x.ok?x.json():null).then(x=>x&&setCards(x.cards??[])).catch(()=>{});useEffect(()=>{load()},[]);
 const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),response=await fetch("/api/cards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({issuer:f.get("issuer"),label:f.get("label"),last4:f.get("last4")})});if(response.ok){setAdding(false);load();setNotice("個人卡已安全登記，只保存末四碼");setTimeout(()=>setNotice(""),2200)}};
 const upload=async()=>{const selected=file.current?.files?.[0];if(!selected)return;const body=new FormData();body.append("file",selected);body.append("documentType","信用卡帳單");if(tripId)body.append("tripId",tripId);const response=await fetch("/api/documents",{method:"POST",body});setNotice(response.ok?"帳單已保存到目前旅程，請回上一步確認資料":"帳單上傳失敗，請重試");setTimeout(()=>setNotice(""),2300)};
 return <section className="card-center panel"><div className="card-center-head"><div><span>我的個人信用卡</span><h2>帳單、收據與手續費分開核對</h2><p>沒有公司卡；每個人只管理自己的卡片與帳單。</p></div><button onClick={()=>setAdding(v=>!v)}>＋ 登記個人卡</button></div>{adding&&<form className="card-form" onSubmit={add}><label>發卡行<input name="issuer" placeholder="例如 中國信託" required/></label><label>卡片名稱<input name="label" placeholder="例如 Elly 差旅卡" required/></label><label>末四碼<input name="last4" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="6072" required/></label><button>安全保存</button></form>}<div className="card-real-layout"><div className="saved-cards">{cards.length?cards.map(c=><article key={c.id}><i>◆</i><span><b>{c.label} •{c.last4}</b><small>{c.issuer}・只保存末四碼</small></span><em>本人私有</em></article>):<article className="no-card"><span><b>尚未登記個人卡</b><small>信用卡付款時，建議先登記卡號末四碼。</small></span></article>}</div><div className="statement-box"><span>目前旅程</span><h3>上傳我的信用卡帳單</h3><p>支援照片、HEIC 與 PDF；上傳後會進入本人的待確認文件匣。</p><button className="statement-upload" onClick={()=>file.current?.click()}>↑ 選擇信用卡帳單</button><input ref={file} type="file" accept="image/*,.heic,.heif,.pdf" hidden onChange={upload}/></div><div className="fee-principle"><span>核對原則</span><h3>三種金額分開保存</h3><ul><li>原始外幣消費</li><li>信用卡台幣請款</li><li>國外交易手續費</li></ul><small>不使用示意金額；只有你確認過的真實資料才會出現在報支。</small></div></div>{notice&&<div className="card-notice">✓ {notice}</div>}</section>
}
