"use client";

import { useMemo, useState } from "react";

export const destinations:Record<string,string[]>={
 "台灣 TWN":["台北 Taipei","高雄 Kaohsiung","嘉義 Chiayi","台中 Taichung","台南 Tainan","宜蘭 Yilan","松山 Taipei Songshan","南投 Nantou","苗栗 Miaoli","桃園 Taoyuan","雲林 Yunlin","新竹 Hsinchu","彰化 Changhua"],
 "中國大陸 CHN":["上海虹橋 Shanghai Hong Qiao","上海浦東 Shanghai Pu Dong","嘉興 Jiaxing","香港 Hong Kong","澳門 Macau","揚州 Yangzhou","廣州 Guangzhou","成都 Chengdu","東莞 DongGuan","南京 Nanjing","北京 Beijing","台州 Taizhou","無錫 Wuxi","杭州 Hangzhou","青島 Qingdao","南昌 Nanchang","南寧 Nanning","泉州 Quanzhou","珠海 Zhuhai","常州 Changzhou","深圳 Shenzhen","長沙 Changsha","廈門 Xiamen","寧波 Ningbo","福州 Fuzhou","鄭州 Zhengzhou"],
 "荷蘭 NLD":["阿姆斯特丹 Amsterdam"],"澳洲 AUS":["雪梨 Sydney","布里斯本 Brisbane","墨爾本 Melbourne"],"西班牙 ESP":["巴塞隆納 Barcelona","拉科魯尼亞 La Coruna","馬德里 Madrid"],"比利時 BEL":["布魯塞爾 Brussels"],"孟加拉 BGD":["達卡 Dhaka"],"柬埔寨 KHM":["金邊 Moha","金邊 MK"],"瑞士 CHE":["日內瓦 Geneva"],
 "加拿大 CAN":["多倫多 Toronto","基洛納 Kelowna","溫哥華 Vancouver"],"丹麥 DNK":["哥本哈根 Copenhagen"],"多明尼加 DOM":["聖多明哥 Santo Domingo"],"埃及 EGY":["開羅 Cairo"],"英國 GBR":["倫敦 London"],"衣索比亞 ETH":["阿迪斯阿貝巴 Addis Ababa","阿瓦薩 Awasa","馬卡勒 Makale","德雷達瓦 Dire Dawa"],
 "法國 FRA":["巴黎 Paris"],"德國 DEU":["法蘭克福 Frankfurt","慕尼黑 Munich","杜塞道夫 Dusseldorf","柏林 Berlin","科隆 Cologne"],"瓜地馬拉 GTM":["瓜地馬拉市 Guatemala City"],"越南 VNM":["河內 Hanoi","河內辦公室 Hanoi Office","胡志明市 Ho Chi Minh City","海防 Hai Phong","芹苴 Can Tho"],"宏都拉斯 HND":["聖佩德羅蘇拉 San Pedro Sula","德古西加巴 Tegucigalpa"],"海地 HTI":["太子港 Port-au-Prince","海地角 Cap-Haïtien"],
 "印度 IND":["孔巴托 Coimbatore","孟買 Mumbai","班加羅爾 Bengaluru","德里 Delhi"],"印尼 IDN":["三寶隆 Semarang","雅加達 Jakarta","峇里島 Bali","梭羅 Solo City","萬隆 Bandung"],"義大利 ITA":["羅馬 Rome","米蘭 Milan"],"約旦 JOR":["安曼 Amman","亞喀巴 Gulf of Aqaba"],"肯亞 KEN":["奈洛比 Nairobi","蒙巴薩 Mombasa"],"賴索托 LSO":["馬塞魯 Maseru"],"緬甸 MMR":["仰光 Yangon"],"馬來西亞 MYS":["吉隆坡 Kuala Lumpur"],
 "紐西蘭 NZL":["奧克蘭 Auckland"],"奧地利 AUT":["維也納 Vienna"],"巴拿馬 PAN":["巴拿馬市 Panama City"],"菲律賓 PHL":["馬尼拉 Manila"],"波蘭 POL":["華沙 Warsaw"],"南非 ZAF":["約翰尼斯堡 Johannesburg"],"新加坡 SGP":["新加坡 Singapore"],"薩爾瓦多 SLV":["聖薩爾瓦多 San Salvador"],"韓國 KOR":["金浦 Gimpo","首爾 Seoul","釜山 Busan"],"泰國 THA":["曼谷 Bangkok"],"土耳其 TUR":["伊斯坦堡 Istanbul"],"日本 JPN":["東京 Tokyo","大阪 Osaka","名古屋 Nagoya"],"阿拉伯聯合大公國 UAE":["杜拜 Dubai"],
 "美國 USA":["明尼亞波利斯 Minneapolis","波士頓 Boston","洛杉磯 Los Angeles","紐約 New York","密爾瓦基 Milwaukee","舊金山 San Francisco","丹佛 Denver","內布拉斯加州 Nebraska","匹茲堡 Pittsburgh","安大略 Ontario CA","北卡羅來納 North Carolina","本頓維爾 Bentonville","休士頓 Houston","米拉洛馬 Mira Loma","西雅圖 Seattle","亞特蘭大 Atlanta","拉斯維加斯 Las Vegas","波特蘭 Portland","芝加哥 Chicago","春田市 Springfield","哥倫布 Columbus","夏威夷 Hawaiian","格林斯伯勒 Greensboro","納什維爾 Nashville","普雷里德欣 Prairie du Chien","華盛頓 Washington","奧蘭多 Orlando","聖地牙哥 San Diego","聖塔安娜 Santa Ana","達拉斯 Dallas","鳳凰城 Phoenix","邁阿密 Miami"]
};

type Stop={country:string;city:string};
export default function CreateTripForm({onCreate}:{onCreate:()=>void}){
 const countries=useMemo(()=>Object.keys(destinations),[]); const [step,setStep]=useState(1); const [stops,setStops]=useState<Stop[]>([{country:"法國 FRA",city:"巴黎 Paris"},{country:"波蘭 POL",city:"華沙 Warsaw"}]);
 const update=(i:number,key:keyof Stop,value:string)=>setStops(v=>v.map((s,n)=>n===i?{...s,[key]:value,...(key==="country"?{city:destinations[value][0]}:{})}:s));
 return <section className="wizard-shell"><div className="wizard-progress">{["基本資料","國家城市","邀請成員"].map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><i>{step>i+1?"✓":i+1}</i><span>{x}</span></div>)}</div><div className="create-card panel wizard-card">{step===1&&<><div><span>步驟 1 / 3</span><h2>建立新出差</h2><p>先填共同範圍，之後都能修改。</p></div><label>出差名稱<input defaultValue="法國・波蘭客戶拜訪"/></label><div className="form-row"><label>開始日期<input type="date" defaultValue="2026-06-15"/></label><label>結束日期<input type="date" defaultValue="2026-06-26"/></label></div></>}{step===2&&<><div><span>步驟 2 / 3</span><h2>選擇國家與城市</h2><p>目前提供 {countries.length} 個國家／地區；先選國家，再篩選城市。</p></div><div className="destination-list">{stops.map((s,i)=><div className="destination-stop" key={i}><b>目的地 {i+1}</b><button onClick={()=>setStops(v=>v.filter((_,n)=>n!==i))} disabled={stops.length===1}>移除</button><label>國家<select value={s.country} onChange={e=>update(i,"country",e.target.value)}>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label>城市<select value={s.city} onChange={e=>update(i,"city",e.target.value)}>{destinations[s.country].map(x=><option key={x}>{x}</option>)}</select></label></div>)}</div><button className="add-destination" onClick={()=>setStops(v=>[...v,{country:"台灣 TWN",city:destinations["台灣 TWN"][0]}])}>＋ 新增另一個國家／城市</button></>}{step===3&&<><div><span>步驟 3 / 3</span><h2>邀請同行者</h2><p>所有成員都能編輯共同活動；每人的報帳仍保持私有。</p></div><label>同行者 Email<input placeholder="輸入 Email 後按加入"/></label><button className="add-destination">＋ 加入另一位同行者</button><div className="wizard-summary"><b>即將建立</b><span>{stops.map(x=>x.city).join(" → ")}</span></div></>}<div className="wizard-footer"><button onClick={()=>setStep(v=>Math.max(1,v-1))} disabled={step===1}>← 上一頁</button>{step<3?<button className="next-page" onClick={()=>setStep(v=>v+1)}>下一頁 →</button>:<button className="next-page" onClick={onCreate}>建立並前往安排行程 →</button>}</div></div></section>
}
