"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import {DEFAULT_CLAIM_TYPES,DEFAULT_CURRENCIES,DEFAULT_DESTINATIONS,normalizeCurrency} from "./managed-config";

type Doc={id:string;originalName:string;mimeType:string;sizeBytes:number;documentType:string;claimType:string|null;expenseDate:string|null;merchant:string|null;currency:string|null;amountMinor:number|null;detectedCurrency:string|null;detectedAmountMinor:number|null;paymentMethod:string|null;cardLast4:string|null;linkedExpenseId:string|null;billedTwdMinor:number|null;suggestedName:string|null;status:string;extractionConfidence:number|null;extractionWarnings:string|null;sourceExcerpt:string|null;createdAt:string};
type Match={id:string;expenseDate:string;merchant:string;category:string;originalCurrency:string|null;originalAmountMinor:number|null;cardLast4:string|null;score:number;reasons:string[]};
const managedCities=Object.entries(DEFAULT_DESTINATIONS).flatMap(([country,cities])=>cities.map(city=>`${country}｜${city}`));
const ext=(name:string)=>name.includes(".")?name.slice(name.lastIndexOf(".")):"";
const safe=(value:string)=>value.trim().replace(/[^\p{L}\p{N}._-]+/gu,"-");
const warnings=(value:string|null)=>{try{return value?JSON.parse(value) as string[]:[]}catch{return[]}};
const isTravelDocument=(value:string)=>value==="flight"||value==="stay"||value.includes("機票")||value.includes("住宿");

export default function DocumentInbox({tripId,refreshKey=0}:{tripId?:string;refreshKey?:number}){
 const [docs,setDocs]=useState<Doc[]>([]);const [open,setOpen]=useState<string|null>(null);const [dirty,setDirty]=useState(false);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState(false);const [message,setMessage]=useState("");const [query,setQuery]=useState("");const [bundling,setBundling]=useState(false);const [pendingAction,setPendingAction]=useState<string|null>(null);const requestSeq=useRef(0);
 const load=useCallback(async()=>{const seq=++requestSeq.current;setLoading(true);setLoadError(false);try{const response=await fetch(`/api/documents${tripId?`?tripId=${encodeURIComponent(tripId)}`:""}`);if(!response.ok)throw new Error("documents_load_failed");const result=await response.json();if(seq!==requestSeq.current)return false;setDocs(result.documents??[]);setLoading(false);return true}catch{if(seq!==requestSeq.current)return false;setDocs([]);setLoadError(true);setLoading(false);return false}},[tripId]);
 useEffect(()=>{setDocs([]);setOpen(null);setDirty(false);setQuery("");setPendingAction(null);void load();return()=>{requestSeq.current++}},[load,refreshKey]);
 useEffect(()=>{const reload=()=>void load();window.addEventListener("tripclaim:data-changed",reload);return()=>window.removeEventListener("tripclaim:data-changed",reload)},[load]);
 const closeEditor=()=>{if(pendingAction)return false;if(dirty&&!window.confirm("放棄這次尚未儲存的文件修改？"))return false;setOpen(null);setDirty(false);return true};
 const toggleEditor=(id:string)=>{if(pendingAction)return;if(open===id){closeEditor();return}if(open&&!closeEditor())return;setOpen(id);setDirty(false)};
 useEffect(()=>{if(!open)return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")closeEditor()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[open,dirty,pendingAction]);
 const save=async(d:Doc,form:HTMLFormElement)=>{if(pendingAction)return;const action=`save:${d.id}`;const fd=new FormData(form);const date=String(fd.get("date")||"");const merchant=String(fd.get("merchant")||"");const cardEvidence=d.documentType.includes("信用卡帳單")||d.documentType.includes("刷卡單");const claimType=cardEvidence?undefined:String(fd.get("claimType")||"餐飲");const originalCurrency=String(d.detectedCurrency??d.currency??"TWD").toUpperCase();const originalAmount=Number(d.detectedAmountMinor??d.amountMinor??0)/100;const reportingCurrency=normalizeCurrency(String(fd.get("reportingCurrency")||"TWD"));const reportingAmount=Number(fd.get("reportingAmount")||0);const city=String(fd.get("city")||"未分類");const paymentMethod=String(fd.get("paymentMethod")||"cash");const cardLast4=String(fd.get("cardLast4")||"");const linkedExpenseId=String(fd.get("linkedExpenseId")||"")||null,billedTwd=Number(fd.get("billedTwd")||0);const suggested=cardEvidence?`EVIDENCE-${date.replaceAll("-","")||"待確認"}_${safe(d.documentType)}_${safe(merchant||"信用卡")}${ext(d.originalName)}`:`EXP-${date.replaceAll("-","")||"待確認"}_${safe(city)}_${safe(claimType||"待確認")}_${safe(merchant||"待確認")}_${reportingCurrency}${reportingAmount||0}_${safe(d.documentType)}${ext(d.originalName)}`;setPendingAction(action);setMessage("正在保存文件資料…");try{const response=await fetch(`/api/documents/${d.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({claimType,expenseDate:date,merchant,originalCurrency,originalAmountMinor:Math.round(originalAmount*100),reportingCurrency,reportingAmountMinor:Math.round(reportingAmount*100),paymentMethod,cardLast4,linkedExpenseId,billedTwdMinor:billedTwd?Math.round(billedTwd*100):null,suggestedName:suggested,status:"ready"})});if(!response.ok){const result=await response.json().catch(()=>null);setMessage(result?.message||"文件保存失敗，請確認申報幣別與金額後重試");return}setDirty(false);setOpen(null);const confirmed=await load();setMessage(confirmed?(cardEvidence?"付款證明已配對保存，不會重複建立消費":"已保留原始金額，並按公司申報幣別加入我的報支"):"文件已保存，但重新讀取失敗；請重新整理確認");setTimeout(()=>setMessage(""),2600)}catch{setMessage("文件保存失敗，網路或伺服器暫時無法回應；未儲存修改仍保留，請重試")}finally{setPendingAction(null)}};
 const remove=async(d:Doc)=>{if(pendingAction)return;const travel=isTravelDocument(d.documentType),name=d.suggestedName||d.originalName,prompt=travel?`確定永久刪除「${name}」所屬的整張機票／住宿訂單？同張訂單的所有航段、共同行程、本人待報支與原始附件都會一起刪除，且無法復原。`:`確定把「${name}」移到垃圾桶？這份一般文件與它建立的費用會暫時隱藏，可立即復原。`;if(!window.confirm(prompt))return;setPendingAction(`delete:${d.id}`);setMessage("正在刪除文件與關聯資料…");try{const response=await fetch(`/api/documents/${d.id}`,{method:"DELETE"});const result=await response.json().catch(()=>null);if(response.ok){setOpen(null);setDirty(false);window.dispatchEvent(new Event("tripclaim:data-changed"));const confirmed=await load();if(result?.recoverable&&result?.undo){setMessage(confirmed?"已移到垃圾桶，可復原":"已移到垃圾桶，但重新讀取失敗；請重新整理確認");if(window.confirm("已移到垃圾桶。要立即復原嗎？")){const restored=await fetch(`/api/trash/${result.undo.kind}/${result.undo.id}`,{method:"POST"});if(restored.ok){window.dispatchEvent(new Event("tripclaim:data-changed"));await load();setMessage("已復原文件與關聯費用")}}}else setMessage(confirmed?"已永久刪除整張 travel 訂單、相關行程與待報支":"永久刪除已送出，但重新讀取失敗；請重新整理確認");setTimeout(()=>setMessage(""),3000)}else setMessage(result?.message||"刪除失敗，請重新整理後再試")}catch{setMessage("刪除失敗，網路或伺服器暫時無法回應；請重試")}finally{setPendingAction(null)}};
 const downloadAll=async()=>{if(!tripId||bundling||pendingAction)return;setBundling(true);setMessage("正在依報支項目與申報幣別建立檔案包…");try{const response=await fetch(`/api/trips/${encodeURIComponent(tripId)}/export`);if(!response.ok)throw new Error("export_failed");const url=URL.createObjectURL(await response.blob()),a=document.createElement("a");a.href=url;a.download=`TripClaim_${new Date().toISOString().slice(0,10)}.zip`;a.click();URL.revokeObjectURL(url);setMessage("已建立報支彙總、明細、附件索引與分組附件")}catch{setMessage("附件打包失敗，請重試")}finally{setBundling(false);setTimeout(()=>setMessage(""),3000)}};
 if(loading)return <section className="document-inbox panel" aria-busy="true"><p role="status" aria-live="polite">正在讀取我的文件…</p></section>;
 if(loadError)return <section className="document-inbox panel"><div className="document-empty"><b>文件載入失敗</b><span>沒有把錯誤狀態當成空文件；請重新讀取。</span><button onClick={()=>void load()}>重新讀取</button></div></section>;
 const normalizedQuery=query.trim().toLowerCase();
 const visible=docs.filter(d=>!normalizedQuery||[d.originalName,d.suggestedName,d.merchant,d.documentType,d.claimType,d.expenseDate,d.currency,d.detectedCurrency].some(x=>x?.toLowerCase().includes(normalizedQuery))),reviewCount=docs.filter(d=>d.status!=="ready").length;
 return <section className="document-inbox panel" aria-busy={Boolean(pendingAction||bundling)}>
<div className="document-head"><div><span>我的文件</span><h2>{docs.length} 份文件</h2><p>{reviewCount?`${reviewCount} 份待確認`:"已全部確認"}・僅本人與授權財務可查看</p></div><div className="document-head-actions"><button disabled={bundling||Boolean(pendingAction)||!docs.length} onClick={downloadAll}>{bundling?"打包中…":"↓ 全部 ZIP"}</button><button disabled={Boolean(pendingAction)||bundling} onClick={()=>void load()}>重新整理</button></div></div>
{docs.length>0&&<div className="document-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋日期、店家、請款類型或檔名"/><b>{visible.length} / {docs.length} 份</b></div>}
{!docs.length?<div className="document-empty"><b>還沒有文件</b><span>點底部「＋ 上傳」即可開始。</span></div>:!visible.length?<div className="document-empty"><b>找不到相符文件</b><span>請換一個日期、店家、類型或檔名關鍵字。</span></div>:<div className="document-list">{visible.map(d=>{const saving=pendingAction===`save:${d.id}`,deleting=pendingAction===`delete:${d.id}`;return <article key={d.id} className="document-row">
<div className="file-kind">{d.mimeType.includes("pdf")?"PDF":"IMG"}</div><div className="file-copy"><b>{d.suggestedName||d.originalName}</b><span>{(d.sizeBytes/1024).toFixed(0)} KB・文件：{d.documentType||"待分類"}・請款：{d.claimType||"待確認"}</span><div className={`document-state ${d.status}`}><strong>{d.status==="ready"?"已確認":d.status==="failed"?"辨識失敗":"待確認"}</strong>{typeof d.extractionConfidence==="number"&&<small>辨識 {d.extractionConfidence}%</small>}{warnings(d.extractionWarnings).length>0&&<em>{warnings(d.extractionWarnings).slice(0,2).join("、")}</em>}</div></div>
<a href={`/api/documents/${d.id}`} target="_blank" rel="noreferrer">查看原檔</a><a className="document-download" href={`/api/documents/${d.id}?download=1`}>下載標準檔名</a><button disabled={Boolean(pendingAction)} aria-expanded={open===d.id} onClick={()=>toggleEditor(d.id)}>{d.status==="ready"?"修改":"確認資料"}</button><button type="button" disabled={Boolean(pendingAction)} className="document-delete" onClick={()=>remove(d)}>{deleting?"刪除中…":"刪除"}</button>
{open===d.id&&<form className="document-editor" aria-busy={saving} onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();void save(d,e.currentTarget)}}>
{(d.documentType.includes("信用卡帳單")||d.documentType.includes("刷卡單"))&&<><p className="card-evidence-note">這是付款證明，不會另建一筆消費。請配對既有費用；國外交易手續費另列為 TWD。</p><CardEvidenceMatcher document={d}/></>}
<label>日期<input name="date" type="date" defaultValue={d.expenseDate??""}/></label>
{!(d.documentType.includes("信用卡帳單")||d.documentType.includes("刷卡單"))&&<><label>國家／城市<select name="city" defaultValue="" required><option value="" disabled>選擇公司主檔中的國家／城市</option>{managedCities.map(x=><option key={x}>{x}</option>)}</select></label><label>報支項目<select name="claimType" defaultValue={d.claimType??(d.documentType.includes("住宿")?"住宿":d.documentType.includes("機票")?"機票(自行刷卡)":d.documentType.includes("交通")?"車資":"餐飲")}>{DEFAULT_CLAIM_TYPES.map(x=><option key={x}>{x}</option>)}</select></label></>}
<label>店家<input name="merchant" defaultValue={d.merchant??""} placeholder="例如 Starbucks"/></label>
{!(d.documentType.includes("信用卡帳單")||d.documentType.includes("刷卡單"))&&<><div className="document-original-money"><b>原始單據金額</b><span>{d.detectedCurrency??d.currency??"待確認"} {((d.detectedAmountMinor??d.amountMinor??0)/100).toLocaleString()}</span><small>原始辨識資料會保留，不會被申報金額覆蓋。</small></div><label>申報幣別<select name="reportingCurrency" defaultValue={normalizeCurrency(d.detectedCurrency??d.currency??"TWD")}>{DEFAULT_CURRENCIES.map(([code,name])=><option key={code} value={code}>{code} {name}</option>)}</select></label>{(d.detectedCurrency??d.currency)&&!DEFAULT_CURRENCIES.some(([code])=>code===(d.detectedCurrency??d.currency))&&<p className="currency-warning">原單據為 {d.detectedCurrency??d.currency}；公司系統僅能以 TWD 報支，請填入實際 TWD 請款金額。</p>}<label>申報金額<input name="reportingAmount" type="number" min="0" step="0.01" required defaultValue={DEFAULT_CURRENCIES.some(([code])=>code===(d.detectedCurrency??d.currency))?(d.detectedAmountMinor??d.amountMinor??0)/100:""}/></label></>}
<label>付款方式<select name="paymentMethod" defaultValue={d.paymentMethod??"cash"}><option value="cash">現金</option><option value="credit_card">個人信用卡</option><option value="other">其他</option></select></label><label>卡號末四碼<input name="cardLast4" inputMode="numeric" maxLength={4} defaultValue={d.cardLast4??""} placeholder="信用卡付款時填寫"/></label><div className="document-editor-actions"><button type="submit" disabled={Boolean(pendingAction)}>{saving?"保存中…":"確認並重新命名"}</button><button type="button" disabled={Boolean(pendingAction)} onClick={()=>closeEditor()}>取消</button></div>
</form>}</article>})}</div>}
{message&&<div className="document-message" role="status" aria-live="polite">{message}</div>}</section>;
}

function CardEvidenceMatcher({document}:{document:Doc}){
 const [matches,setMatches]=useState<Match[]>([]),[ambiguous,setAmbiguous]=useState(false),[matchState,setMatchState]=useState<"loading"|"ready"|"error">("loading"),[retryKey,setRetryKey]=useState(0);
 useEffect(()=>{let active=true;setMatchState("loading");void(async()=>{try{const response=await fetch(`/api/documents/${document.id}/matches`);if(!response.ok)throw new Error("matches_load_failed");const result=await response.json();if(!active)return;setMatches(result?.candidates??[]);setAmbiguous(Boolean(result?.ambiguous));setMatchState("ready")}catch{if(!active)return;setMatches([]);setAmbiguous(false);setMatchState("error")}})();return()=>{active=false}},[document.id,retryKey]);
 return <div className="card-match-box"><label>帳單 TWD 實際請款<input name="billedTwd" type="number" min="0" step="0.01" defaultValue={document.billedTwdMinor?document.billedTwdMinor/100:""} placeholder="不含手續費"/></label><label>配對既有費用<select name="linkedExpenseId" defaultValue={document.linkedExpenseId??""} disabled={matchState==="loading"}><option value="">尚未配對</option>{matches.map(x=><option value={x.id} key={x.id}>{x.expenseDate}｜{x.merchant}｜{x.originalCurrency} {((x.originalAmountMinor??0)/100).toFixed(2)}｜{x.score}%</option>)}</select></label>{matchState==="loading"&&<small role="status">正在尋找可配對的本人費用…</small>}{matchState==="error"&&<p role="alert">配對候選載入失敗；可先保存帳單，或<button type="button" onClick={()=>setRetryKey(value=>value+1)}>重新嘗試</button>。</p>}{matchState==="ready"&&ambiguous&&<p>找到多筆相近交易，請人工選擇；系統不會自行猜測。</p>}{matchState==="ready"&&!matches.length&&<small>目前沒有可安全配對的本人費用，先保存帳單，之後補收據仍可再配對。</small>}</div>;
}
