"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import AgendaSheet,{blankForCell} from "./AgendaSheet";
import BookingPanel from "./BookingPanel";
import TripTodoPanel from "./TripTodoPanel";
import CompLeavePanel from "./CompLeavePanel";
import {calendarDatesForAgenda} from "./agenda-flight-layout.js";
type Agenda={id:string;type:string;title:string;startsAt:string;endsAt?:string|null;timezone?:string|null;place?:string|null;address?:string|null;notes?:string|null;version:number;departureTimezone?:string|null;departureUtcAt?:string|null;arrivalTimezone?:string|null;arrivalUtcAt?:string|null;origin?:string|null;destination?:string|null};
type BookingTimezone={id:string;departureTimezone?:string|null;departureUtcAt?:string|null;arrivalTimezone?:string|null;arrivalUtcAt?:string|null;origin?:string|null;destination?:string|null};
const isSyncedTravel=(row:Agenda)=>Boolean(row.notes?.startsWith("booking:"));
export default function ItineraryWizardLive({tripId}:{tripId:string}){
 const [rows,setRows]=useState<Agenda[]>([]),[dates,setDates]=useState<string[]>([]),[draft,setDraft]=useState<Agenda|null>(null),[status,setStatus]=useState("正在載入行程…"),[busy,setBusy]=useState<null|"save"|"delete">(null);
 const requestSeq=useRef(0);
 const load=useCallback(async(id:string)=>{if(!id)return false;const seq=++requestSeq.current;setStatus("正在載入行程…");try{const r=await fetch(`/api/trips/${id}/summary`);if(!r.ok)throw new Error("load_failed");const x=await r.json();if(seq!==requestSeq.current)return false;const bookings=(x.bookings??[]) as BookingTimezone[],bookingById=new Map(bookings.map(booking=>[booking.id,booking]));const agenda=((x.agenda??[]) as Agenda[]).map(row=>{const bookingId=row.notes?.startsWith("booking:")?row.notes.slice(8):null,booking=bookingId?bookingById.get(bookingId):null;return booking?{...row,departureTimezone:booking.departureTimezone,departureUtcAt:booking.departureUtcAt,arrivalTimezone:booking.arrivalTimezone,arrivalUtcAt:booking.arrivalUtcAt,origin:booking.origin,destination:booking.destination}:row});setRows(agenda);setDates(x.trip?calendarDatesForAgenda(x.trip.startsOn,x.trip.endsOn,agenda):[]);setStatus(agenda.length?"已同步最新行程":"尚無行程；可先上傳機票／住宿，或直接新增活動");return true}catch{if(seq!==requestSeq.current)return false;setRows([]);setDates([]);setStatus("載入失敗，請重新整理");return false}},[]);
 useEffect(()=>{setRows([]);setDates([]);setDraft(null);setBusy(null);void load(tripId);const reload=()=>void load(tripId);window.addEventListener("tripclaim:data-changed",reload);return()=>{requestSeq.current++;window.removeEventListener("tripclaim:data-changed",reload)}},[tripId,load]);
 const updateDraft=(key:keyof Agenda,value:string)=>setDraft(row=>row?{...row,[key]:value}:row);
 const updateTime=(row:Agenda,key:"startsAt"|"endsAt",time:string)=>updateDraft(key,`${row.startsAt.slice(0,10)}T${time}`);
 const toggleAllDay=(row:Agenda,checked:boolean)=>setDraft({...row,type:checked?"全天":row.type==="全天"?"會議":row.type,startsAt:`${row.startsAt.slice(0,10)}T${checked?"00:00":row.type==="全天"?"09:00":row.startsAt.slice(11,16)}`,endsAt:checked?null:row.endsAt});
 const add=()=>{if(busy||!tripId||!dates.length)return;setDraft(blankForCell(dates[0],"09:00"));setStatus("尚未儲存；完成資料後按保存")};
 const addAt=(date:string,time:string)=>{if(busy)return;setDraft(blankForCell(date,time));setStatus("尚未儲存；完成資料後按保存")};
 const edit=(row:Agenda)=>{if(busy)return;if(isSyncedTravel(row)){setStatus("機票與住宿由來源訂單同步；請直接用上方「我的行程資料」重新上傳／登記");return}setDraft({...row});setStatus("正在編輯；按保存後才會同步給同行者")};
 const cancelDraft=()=>{if(busy)return;setDraft(null);setStatus(rows.length?"已同步最新行程":"尚無行程；可先上傳機票／住宿，或直接新增活動")};
 const save=async(row:Agenda)=>{if(busy)return;if(isSyncedTravel(row)){setDraft(null);setStatus("機票與住宿由來源訂單同步；請直接用上方「我的行程資料」重新上傳／登記");return}setBusy("save");setStatus("正在保存…");try{if(row.version===0){const r=await fetch(`/api/trips/${tripId}/agenda`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(row)});if(!r.ok){setStatus("保存失敗，未儲存內容仍保留在編輯區；請重試");return}setDraft(null);const confirmed=await load(tripId);setStatus(confirmed?"已保存並同步給同行者":"活動已送出，但重新讀取失敗；請重新整理確認");return}const r=await fetch(`/api/trips/${tripId}/agenda/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(row)});if(r.status===409){const x=await r.json().catch(()=>null);setStatus(x?.error==="managed_travel_item"?"機票與住宿由來源訂單同步；請直接用上方「我的行程資料」重新上傳／登記":"其他同行者剛修改這筆資料，未覆蓋對方版本；請重新載入後再確認");return}if(!r.ok){setStatus("保存失敗，未儲存修改仍保留在編輯區；請重試或取消");return}setDraft(null);const confirmed=await load(tripId);setStatus(confirmed?"已保存並同步給同行者":"修改已送出，但重新讀取失敗；請重新整理確認")}catch{setStatus("保存失敗，網路或伺服器暫時無法回應；未儲存修改仍保留，請重試")}finally{setBusy(null)}};
 const remove=async(row:Agenda)=>{if(busy)return;const travel=isSyncedTravel(row);if(!window.confirm(travel?`確定永久刪除「${row.title}」所屬的整張機票／住宿訂單？同張訂單的所有航段、附件與本人待報支會一起刪除，且無法復原。`:`確定刪除「${row.title}」？`))return;setBusy("delete");setStatus(travel?"正在永久刪除整張訂單…":"正在刪除活動…");try{const r=await fetch(`/api/trips/${tripId}/agenda/${row.id}`,{method:"DELETE"});const result=await r.json().catch(()=>null);if(r.ok){setDraft(current=>current?.id===row.id?null:current);window.dispatchEvent(new Event("tripclaim:data-changed"));await load(tripId);setStatus(result?.travelOrder?`已永久刪除整張訂單（${result.bookingsDeleted??1} 段）`:"已刪除並保留復原紀錄")}else if(r.status===403&&result?.error==="travel_booking_owner_only")setStatus("這是同行者的機票／住宿，只有訂單本人可以刪除");else setStatus(result?.message||"刪除失敗，請重試")}catch{setStatus("刪除失敗，網路或伺服器暫時無法回應；請重試")}finally{setBusy(null)}};
 return <main className="wizard-page itinerary-wizard itinerary-workspace-page simplified-itinerary-page calendar-primary-page">
  <section className="wizard-stage itinerary-single">
   <div className="step-heading"><h1>行程</h1><p>上傳機票／住宿後會直接排進行事曆；其他活動直接點日曆新增。</p><button className="add-agenda" onClick={add} disabled={busy!==null||!tripId||!dates.length}>＋ 新增活動</button></div>
   <section className="itinerary-inline-prep itinerary-primary-intake" aria-label="我的行程資料"><TripTodoPanel tripId={tripId} onBookingSaved={()=>void load(tripId)}/></section>
   <p className="sync-line" role="status" aria-live="polite">{status}</p>
   <div className="agenda-workspace shared-only"><div className="agenda-workspace-main">
    <AgendaSheet dates={dates} rows={rows} onAdd={addAt} onEdit={edit} onDelete={remove}/>
    {draft&&!isSyncedTravel(draft)&&<article className="agenda-sheet-editor panel" key={`${draft.id}-${draft.version}`}><div className="agenda-edit-grid"><label className="all-day-check"><input type="checkbox" checked={draft.type==="全天"} disabled={busy!==null} onChange={e=>toggleAllDay(draft,e.target.checked)}/><span><b>全天活動</b><small>不需要填開始與結束時間</small></span></label>{draft.type!=="全天"&&<><label>開始時間<input type="time" value={draft.startsAt.slice(11,16)} disabled={busy!==null} onChange={e=>updateTime(draft,"startsAt",e.target.value)}/></label><label>結束時間<input type="time" value={(draft.endsAt??"").slice(11,16)} disabled={busy!==null} onChange={e=>updateTime(draft,"endsAt",e.target.value)}/></label></>}<label className="activity-field">活動<input value={draft.title} disabled={busy!==null} placeholder="例如：拜訪客戶、午餐" onChange={e=>updateDraft("title",e.target.value)}/></label><label className="people-field">參與者<input value={draft.place??""} disabled={busy!==null} placeholder="輸入姓名，可用逗號分隔" onChange={e=>updateDraft("place",e.target.value)}/></label></div><div className="agenda-item-actions"><button disabled={busy!==null||!draft.title.trim()} onClick={()=>save(draft)}>{busy==="save"?"保存中…":"✓ 保存"}</button><button disabled={busy!==null} onClick={cancelDraft}>取消</button>{draft.version>0&&<button className="delete" disabled={busy!==null} onClick={()=>remove(draft)}>{busy==="delete"?"刪除中…":"刪除"}</button>}</div></article>}
    <details className="itinerary-secondary-tools panel"><summary>補休與同行者機票／住宿</summary><div className="itinerary-secondary-grid"><CompLeavePanel tripId={tripId}/><section className="shared-booking-overview" aria-label="同行者機票與住宿"><BookingPanel tripId={tripId}/></section></div></details>
   </div></div>
  </section>
 </main>;
}