"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import PersistentTravelDocuments from "./PersistentTravelDocuments";
import CreateTripForm from "./CreateTripWizardLive";
import DocumentInbox from "./DocumentInbox";
import CardCenter from "./CardCenter";
import ExpenseWizard from "./ExpenseWizardLive";
import ExpensePageBoundary from "./ExpensePageBoundary";
import ItineraryWizard from "./ItineraryWizardLive";
import SystemManagement from "./SystemManagement";

type Expense={id:number;date:string;merchant:string;city:string;category:string;currency:string;amount:number;twd:number;payment:string;file:string;state:"ready"|"review"|"missing"};
type ActiveTrip={id:string;name:string};
const placeMap:Record<string,string[]>={
  "法國":["巴黎 Paris"],"波蘭":["華沙 Warsaw"],"美國":["明尼亞波利斯 Minneapolis","波士頓 Boston","洛杉磯 Los Angeles","紐約 New York","舊金山 San Francisco","西雅圖 Seattle","亞特蘭大 Atlanta","拉斯維加斯 Las Vegas","波特蘭 Portland","芝加哥 Chicago","邁阿密 Miami"],
  "中國大陸":["上海 Shanghai","嘉興 Jiaxing","香港 Hong Kong","澳門 Macau","揚州 Yangzhou","廣州 Guangzhou","成都 Chengdu","東莞 Dongguan","南京 Nanjing","北京 Beijing","深圳 Shenzhen","廈門 Xiamen","寧波 Ningbo","杭州 Hangzhou","青島 Qingdao"],
  "台灣":["台北 Taipei","高雄 Kaohsiung","嘉義 Chiayi","台中 Taichung","台南 Tainan","宜蘭 Yilan","桃園 Taoyuan","新竹 Hsinchu"],"日本":["東京 Tokyo","大阪 Osaka","名古屋 Nagoya"],"韓國":["首爾 Seoul","釜山 Busan"],"澳洲":["雪梨 Sydney","布里斯本 Brisbane","墨爾本 Melbourne"],"德國":["法蘭克福 Frankfurt","慕尼黑 Munich","柏林 Berlin"],"越南":["河內 Hanoi","胡志明市 Ho Chi Minh City"],"印度":["孔巴托 Coimbatore","孟買 Mumbai","班加羅爾 Bengaluru","德里 Delhi"],"印尼":["三寶隆 Semarang","雅加達 Jakarta","峇里島 Bali"],"新加坡":["新加坡 Singapore"],"泰國":["曼谷 Bangkok"],"英國":["倫敦 London"],"義大利":["羅馬 Rome","米蘭 Milan"],"荷蘭":["阿姆斯特丹 Amsterdam"],"西班牙":["巴塞隆納 Barcelona","馬德里 Madrid"],"瑞士":["日內瓦 Geneva"],"加拿大":["多倫多 Toronto","溫哥華 Vancouver"],"菲律賓":["馬尼拉 Manila"],"馬來西亞":["吉隆坡 Kuala Lumpur"],"土耳其":["伊斯坦堡 Istanbul"],"阿聯酋":["杜拜 Dubai"]
};
const seed:Expense[]=[
 {id:1,date:"06/15",merchant:"EVA Air",city:"巴黎",category:"機票",currency:"TWD",amount:86837,twd:86837,payment:"Elly 個人卡 •6072",file:"EXP-0615-001_機票.pdf",state:"ready"},
 {id:2,date:"06/16",merchant:"Hôtel Le Six",city:"巴黎",category:"住宿",currency:"EUR",amount:624,twd:22662,payment:"Elly 個人卡 •6072",file:"EXP-0616-002_住宿.pdf",state:"ready"},
 {id:3,date:"06/18",merchant:"Café Kitsuné",city:"巴黎",category:"餐飲",currency:"EUR",amount:38.6,twd:1402,payment:"Elly 個人卡 •2819",file:"EXP-0618-003_收據.jpg",state:"review"},
 {id:4,date:"06/21",merchant:"SNCF Connect",city:"巴黎→華沙",category:"交通",currency:"EUR",amount:102.95,twd:3740,payment:"Elly 個人卡 •6072",file:"EXP-0621-004_票券.pdf",state:"ready"},
 {id:5,date:"06/22",merchant:"Warsaw Bistro",city:"華沙",category:"餐飲",currency:"PLN",amount:191.52,twd:1696,payment:"Elly 個人卡 •6072",file:"EXP-0622-005_收據.jpg",state:"missing"},
 {id:6,date:"06/24",merchant:"Polonia Palace",city:"華沙",category:"住宿",currency:"PLN",amount:3344,twd:29609,payment:"Elly 個人卡 •6072",file:"EXP-0624-006_住宿.png",state:"missing"}
];
const fmt=(n:number)=>new Intl.NumberFormat("zh-TW").format(Math.round(n));

export default function Home(){
 const [items,setItems]=useState(seed);const [stage,setStage]=useState<"create"|"itinerary"|"expense">("create");const [view,setView]=useState<"inbox"|"missing"|"plan">("inbox");const [country,setCountry]=useState("法國");const [city,setCity]=useState("巴黎 Paris");const [share,setShare]=useState(false);const [manage,setManage]=useState<"personal"|"admin"|null>(null);const [toast,setToast]=useState("");const [processing,setProcessing]=useState(false);const [filter,setFilter]=useState("全部");const fileRef=useRef<HTMLInputElement>(null);
 const [activeTrip,setActiveTrip]=useState<ActiveTrip|null>(null);
 const [account,setAccount]=useState({displayName:"Elly Cheng",email:"elly@example.com",notificationEmail:"elly@example.com",authenticated:false});
 useEffect(()=>{fetch("/api/me").then(x=>x.json()).then(x=>x?.email&&setAccount({...x,authenticated:true})).catch(()=>{})},[]);
 const total=useMemo(()=>items.reduce((a,b)=>a+b.twd,0),[items]);const show=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2300)};
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setProcessing(true);const selected=Array.from(files);const results=await Promise.all(selected.map(async f=>{const body=new FormData();body.append("file",f);body.append("documentType","receipt");return fetch("/api/documents",{method:"POST",body}).then(x=>x.ok).catch(()=>false)}));const add=selected.map((f,i)=>({id:Date.now()+i,date:"今天",merchant:results[i]?"已永久保存・AI 辨識中":"上傳待重試",city:city.split(" ")[0],category:"待確認",currency:"—",amount:0,twd:0,payment:"待判斷",file:f.name,state:"review" as const}));setItems(v=>[...add,...v]);setProcessing(false);const saved=results.filter(Boolean).length;show(saved===selected.length?`${saved} 份單據已永久保存，現在可以繼續趕行程`:`已保存 ${saved} 份，${selected.length-saved} 份需要重試`)};
 const visible=items.filter(x=>filter==="全部"||(filter==="待確認"&&x.state==="review")||(filter==="缺件"&&x.state==="missing"));
 const goTrips=()=>{setStage("create");setActiveTrip(null)};
 const openTrip=(trip:ActiveTrip,target:"itinerary"|"expense")=>{setActiveTrip(trip);setStage(target)};
 const scrollExpense=(selector:string)=>{setStage("expense");setTimeout(()=>document.querySelector(selector)?.scrollIntoView({behavior:"smooth",block:"start"}),80)};
 const needsTrip=(action:()=>void)=>activeTrip?action():show("請先建立或選擇一趟出差");
 const mobileBottomNav=<nav className="mobile-nav" aria-label="手機主要功能">
  <button className={stage==="create"?"on":""} onClick={goTrips}><i>⌂</i><span>出差</span></button>
  <button className={stage==="itinerary"?"on":""} aria-disabled={!activeTrip} onClick={()=>needsTrip(()=>setStage("itinerary"))}><i>▤</i><span>今日</span></button>
  <button className="camera" aria-disabled={!activeTrip} onClick={()=>needsTrip(()=>{setStage("expense");setTimeout(()=>window.dispatchEvent(new Event("tripclaim:upload")),80)})}><i>＋</i><span>上傳</span></button>
  <button aria-disabled={!activeTrip} onClick={()=>needsTrip(()=>scrollExpense(".missing-live"))}><i>!</i><span>待辦</span></button>
  <button onClick={()=>setManage("personal")}><i>●</i><span>我的</span></button>
 </nav>;
 const management=manage&&<SystemManagement account={account} mode={manage} onClose={()=>setManage(null)} onProfileSaved={profile=>setAccount(current=>({...current,...profile}))}/>;
 const appHeader=<header className="topbar"><div className="topbar-inner"><div className="brand"><span>快</span><div><b>快報</b><small>TripClaim</small></div></div><nav aria-label="主要流程"><button className={stage==="create"?"active":""} onClick={goTrips}><i>1</i>我的出差</button><button disabled={!activeTrip} className={stage==="itinerary"?"active":""} onClick={()=>activeTrip&&setStage("itinerary")}><i>2</i>共同行程</button><button disabled={!activeTrip} className={stage==="expense"?"active":""} onClick={()=>activeTrip&&setStage("expense")}><i>3</i>我的報帳</button></nav><div className="account-spacer"/><button className="management-trigger" onClick={()=>setManage("admin")}>管理</button><button className="account-menu" onClick={()=>setManage("personal")}><span className="account-name"><b>{account.displayName}</b><small>{account.authenticated?"已登入・個人資料":"示範帳號"}</small></span><span className="profile" title={account.email}>{account.displayName.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</span></button></div></header>;
 const tripContext=activeTrip&&<section className="trip-context-nav"><button className="back" onClick={goTrips}>← 全部出差</button><div><span>目前出差</span><b>{activeTrip.name}</b></div></section>;
 if(stage==="expense")return <>{appHeader}{tripContext}<ExpensePageBoundary onBack={()=>setStage("itinerary")}><ExpenseWizard onBack={()=>setStage("itinerary")}/></ExpensePageBoundary>{mobileBottomNav}{management}</>;
 if(stage==="itinerary")return <>{appHeader}{tripContext}<ItineraryWizard/>{mobileBottomNav}{management}</>;
 return <main>
  {appHeader}
  {management}
  {stage==="create"?<CreateTripForm onCreate={trip=>openTrip(trip,"itinerary")} onExpense={trip=>openTrip(trip,"expense")}/>:stage==="itinerary"?<><Itinerary onInvite={()=>setShare(true)} onContinue={()=>setStage("expense")}/><CollaborativeNotice/><TodayBoard onUpload={()=>fileRef.current?.click()}/><DailyAgenda/><PersistentTravelDocuments/><MyFlight/></>:<section className="shell">
   <div className="mobile-trip-head"><div><span className="live">● 進行中</span><h1>法國・波蘭</h1><p>06/15–06/26 · 4 人同行</p></div><button onClick={()=>setShare(true)}>↗</button></div>
   <div className="tripbar"><div><span className="live">● 我的報帳</span><h1>Elly｜法國・波蘭出差</h1><p>共同行程已帶入；此頁只顯示 Elly 自己付款、自己申報的費用</p></div><div className="completeness"><div><span>我的報帳完整度</span><b>82%</b></div><i><em></em></i><small>還有 3 項需要處理</small></div></div>
   <div className="quick"><div className="quick-copy"><span>旅行模式</span><h2>現在只要把單據丟進來。</h2><p>不用分類、不用填金額；AI 會依出差日期與城市整理，回國後只確認例外。</p></div><div className="location"><label>目前國家<select value={country} onChange={e=>{setCountry(e.target.value);setCity(placeMap[e.target.value][0])}}>{Object.keys(placeMap).map(x=><option key={x}>{x}</option>)}</select></label><span>→</span><label>城市<select value={city} onChange={e=>setCity(e.target.value)}>{placeMap[country].map(x=><option key={x}>{x}</option>)}</select></label></div><button className={`capture ${processing?"busy":""}`} onClick={()=>fileRef.current?.click()}><input ref={fileRef} type="file" accept="image/*,.pdf" multiple capture="environment" onChange={e=>upload(e.target.files)}/><strong>{processing?"辨識中…":"＋ 拍照／上傳單據"}</strong><small>可多選圖片、PDF、電子票券</small></button></div>
   <DocumentInbox/><CardCenter/><div className="stats"><button onClick={()=>{setView("inbox");setFilter("全部")}} className={view==="inbox"&&filter==="全部"?"on":""}><span>文件</span><b>{items.length}</b><small>已全部安全保存</small></button><button onClick={()=>{setView("inbox");setFilter("待確認")}}><span>待確認</span><b>{items.filter(x=>x.state==="review").length}</b><small>只問 AI 不確定的</small></button><button onClick={()=>{setView("missing");setFilter("缺件")}} className={view==="missing"?"warn":""}><span>缺件</span><b>{items.filter(x=>x.state==="missing").length}</b><small>帳單、簽單或明細</small></button><button><span>報支總額</span><b>NT$ {fmt(total)}</b><small>已辨識費用</small></button></div>

   {view==="plan"?<Plan/>:<div className="content"><section className="inbox panel"><div className="panel-title"><div><h2>{view==="missing"?"缺件中心":"確認匣"}</h2><p>{view==="missing"?"依付款方式主動告訴你還缺什麼":"系統已處理確定項目，你只需要看例外"}</p></div><div className="seg">{["全部","待確認","缺件"].map(x=><button className={filter===x?"on":""} onClick={()=>{setFilter(x);if(x==="缺件")setView("missing");else setView("inbox")}} key={x}>{x}</button>)}</div></div>
    {visible.map(x=><article className={`expense ${x.state}`} key={x.id}><div className="receipt">{x.file.endsWith("pdf")?"PDF":"IMG"}</div><div className="expense-main"><div className="expense-line"><span>{x.date}</span><h3>{x.merchant}</h3><em>{x.city}</em></div><p>{x.category} · {x.payment}</p><small>建議檔名：{x.date.replace("/","")}_{x.city}_{x.category}_{x.merchant}_{x.currency}{x.amount}_{x.file.split("_").pop()}</small></div><div className="money"><small>{x.currency}</small><b>{x.amount?fmt(x.amount):"—"}</b><span>NT$ {fmt(x.twd)}</span></div><div className="state">{x.state==="ready"?<span className="ok">✓ 完成</span>:x.state==="review"?<button onClick={()=>{setItems(v=>v.map(i=>i.id===x.id?{...i,state:"ready"}:i));show("已確認並重新命名")}}>確認金額</button>:<button onClick={()=>show("請上傳同卡號末四碼的信用卡帳單")}>缺信用卡帳單</button>}</div></article>)}
   </section><aside className="side"><div className="panel missing-card"><div className="side-title"><span>⚡</span><div><h3>我的信用卡缺件</h3><p>報帳資料只屬於目前登入者</p></div></div><div className="alert"><b>Elly 個人卡 •6072</b><span>2 筆尚缺個人信用卡帳單</span><button onClick={()=>fileRef.current?.click()}>上傳我的信用卡帳單</button></div><ul><li><i className="done">✓</i> 我的原始收據 6 / 6</li><li><i className="done">✓</i> 我的刷卡簽單 4 / 4</li><li><i>!</i> 個人信用卡帳單 0 / 1</li><li><i>!</i> 國外手續費證明 0 / 1</li></ul><small>只配對 Elly 本人的卡片，依日期、店家、外幣金額與卡號末四碼核對。</small></div><div className="panel next"><span>我的報帳</span><h3>先處理 3 個例外，其他 15 筆不用看。</h3><button onClick={()=>show("已跳到第一個例外")}>開始快速確認 →</button></div></aside></div>}
  </section>}
  {share&&<div className="overlay" onClick={()=>setShare(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setShare(false)}>×</button><span className="modal-icon">↗</span><h2>邀請同行者一起對齊行程</h2><p>行前共同確認航班、住宿與拜訪安排；行程確認後，系統才產生出差申請單並帶入後續報帳。</p><div className="invite"><input placeholder="輸入同事 Email 或員編"/><select><option>可編輯行程</option><option>僅可查看</option></select><button onClick={()=>show("行程邀請已寄出")}>邀請</button></div><h4>同行成員</h4>{[["AL","Alan Liu","可編輯行程"],["KC","Karen Chen","可編輯行程"],["YC","Yoko Chen","僅可查看"]].map(x=><div className="member" key={x[1]}><i>{x[0]}</i><span><b>{x[1]}</b><small>聚陽實業</small></span><select defaultValue={x[2]}><option>可編輯行程</option><option>僅可查看</option><option>移除</option></select></div>)}<button className="copy" onClick={()=>show("行程連結已複製")}>⧉ 複製行程連結</button></div></div>}
  {mobileBottomNav}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}

function CollaborativeNotice(){return <section className="collab-notice"><div><span>✎</span><p><b>所有同行者都可以編輯</b><small>新增或修改會記錄編輯者與時間，大家看到的是同一份最新行程。</small></p></div><div className="edit-log"><i>AL</i><span>Alan 於 8 分鐘前更新華沙會議</span></div></section>}

function TodayBoard({onUpload}:{onUpload:()=>void}){return <section className="today-board panel"><div className="today-title"><span>今天・巴黎當地時間</span><h2>星期三，6 月 17 日</h2><p>下一站 10:00，步行約 12 分鐘</p></div><div className="next-stop"><small>下一站</small><strong>Meet at Bacha Café</strong><span>10:00–11:30・Laure、Marcel</span><p>30 rue du Faubourg Saint-Honoré, Paris</p><button>開啟導航 ↗</button></div><div className="today-meals"><div><small>早餐 08:00</small><b>飯店早餐</b></div><div><small>午餐 12:30</small><b>Bacha Café 周邊</b></div><div><small>晚餐 19:00</small><b>Le Procope</b></div></div><div className="tonight"><small>今晚住宿</small><b>Numa Paris Champs-Élysées</b><span>我的住宿・已 Check-in</span></div><button className="today-upload" onClick={onUpload}><strong>＋ 拍照／上傳單據</strong><span>拿到就丟進來，不必現在整理</span></button></section>}

function TravelDocuments(){const ref=useRef<HTMLInputElement>(null);const [kind,setKind]=useState<"機票"|"住宿"|null>(null);const [step,setStep]=useState<"pick"|"reading"|"confirm"|"done">("pick");const start=(type:"機票"|"住宿")=>{setKind(type);setStep("pick");setTimeout(()=>ref.current?.click(),0)};const picked=()=>{setStep("reading");setTimeout(()=>setStep("confirm"),900)};const confirm=()=>{setStep("done");setTimeout(()=>{setKind(null);setStep("pick")},1800)};return <section className="docs-shell"><div className="docs-head"><div><span>個人交通與住宿</span><h2>每個人可以住不同地方</h2><p>每位同行者登入後只維護自己的安排；分享頁只顯示必要摘要。</p></div><div className="sync-badge">✓ 上傳一次，同步行程與我的報支</div></div><div className="docs-grid">{[["EC","Elly","BR087 台北 → 巴黎","Numa Paris Champs-Élysées"],["AL","Alan","BR087 台北 → 巴黎","Novotel Paris Centre"],["KC","Karen","06/16 AF557 香港 → 巴黎","Numa Paris Champs-Élysées"],["YC","Yoko","06/16 AF557 香港 → 巴黎","Mercure Paris Centre"]].map((x,i)=><article className={`person-doc panel ${i===0?"mine":""}`} key={x[1]}><div className="person-name"><i>{x[0]}</i><span><b>{x[1]}</b><small>{i===0?"我的個人安排":"共享摘要"}</small></span>{i===0?<em>只有我可改</em>:<em className="summary-only">僅顯示摘要</em>}</div><div className="doc-line"><span>✈ 機票</span><b>{x[2]}</b>{i===0?<button onClick={()=>start("機票")}>重新上傳</button>:<small>票價與付款不公開</small>}</div><div className="doc-line"><span>⌂ 住宿</span><b>{x[3]}</b>{i===0?<button onClick={()=>start("住宿")}>補住宿文件</button>:<small>房價與附件不公開</small>}</div></article>)}</div><input ref={ref} type="file" accept="image/*,.pdf" hidden onChange={picked}/>{kind&&<div className="travel-overlay"><div className="travel-dialog panel"><button className="x" onClick={()=>setKind(null)}>×</button>{step==="reading"?<div className="reading"><i></i><h3>正在讀取{kind}…</h3><p>你可以先離開，完成後會通知。</p></div>:step==="confirm"?<><span className="recognize">AI 辨識結果・請確認</span><h2>{kind==="機票"?"BR087・台北 → 巴黎":"Numa Paris Champs-Élysées"}</h2><div className="recognized-fields">{(kind==="機票"?[["旅客","Elly Cheng"],["出發","2026/06/15 23:30・桃園 TPE"],["抵達","2026/06/16 08:05・巴黎 CDG"],["金額","TWD 86,837・個人卡 •6072"]]:[["住客","Elly Cheng"],["入住","2026/06/16"],["退房","2026/06/21"],["金額","EUR 624.00・個人卡 •6072"]]).map(x=><label key={x[0]}><span>{x[0]}</span><input defaultValue={x[1]}/></label>)}</div><label className="dual-check"><input type="checkbox" defaultChecked/><span><b>加入我的行程</b><small>同行者只會看到時間、地點與必要摘要</small></span></label><label className="dual-check"><input type="checkbox" defaultChecked/><span><b>建立我的待報支</b><small>金額、卡片與文件只有我及授權財務可見</small></span></label><button className="confirm-travel" onClick={confirm}>確認並同步兩邊</button></>:step==="done"?<div className="reading done"><strong>✓</strong><h3>已同步完成</h3><p>{kind}已加入個人行程與個人待報支。</p></div>:null}</div></div>}</section>}

function DailyAgenda(){const [editing,setEditing]=useState(false);const [saved,setSaved]=useState(false);const days=[{date:"06/16",day:"二",topic:"抵達巴黎・入住",stay:"Numa Paris Champs-Élysées",items:[["08:05","抵達 CDG／接機","Paris CDG → 飯店","交通"],["09:30","早餐・飯店附近","依抵達狀況彈性安排","早餐"],["12:30","午餐・Bofinger","與 Baptiste","午餐"],["15:00","飯店 Check-in／休息","Numa Paris Champs-Élysées","活動"],["19:00","晚餐・自由安排","巴黎市區","晚餐"]]},{date:"06/17",day:"三",topic:"法國合作方會議",stay:"Numa Paris Champs-Élysées",items:[["08:00","飯店早餐","Numa Paris Champs-Élysées","早餐"],["10:00","Meet at Bacha Café","Laure、Marcel","會議"],["12:30","午餐","Bacha Café 周邊","午餐"],["14:00","Luxurynsight Meeting","合作計畫與資料確認","會議"],["19:00","晚餐・Le Procope","Vanessa、Elly、合作方","晚餐"]]},{date:"06/18",day:"四",topic:"品牌與學校拜訪",stay:"Numa Paris Champs-Élysées",items:[["08:00","飯店早餐","飯店","早餐"],["09:30","LY Meeting","98bis rue de la Folie Méricourt","會議"],["12:30","午餐・Leon","Reginald（美法投資人）","午餐"],["13:30","Visit PCA","Paris College of Art","拜訪"],["15:00","Visit Carlin","趨勢與設計交流","拜訪"],["19:00","晚餐・自由安排","巴黎市區","晚餐"]]}];return <section className="agenda-shell"><div className="agenda-head"><div><span>共同行程・所有同行者可編輯</span><h2>每日詳細行程</h2><p>會議、三餐、地址、住宿與參考資料集中在一起。</p></div><div className="agenda-actions"><button className="active">列表</button><button>日曆</button><button className="add-shared" onClick={()=>setEditing(v=>!v)}>＋ 新增共同活動</button></div></div>{editing&&<div className="agenda-composer panel"><label>日期<input type="date" defaultValue="2026-06-17"/></label><label>時間<input type="time" defaultValue="16:30"/></label><label>類型<select><option>會議</option><option>早餐</option><option>午餐</option><option>晚餐</option><option>交通</option></select></label><label className="wide">活動名稱<input defaultValue="客戶會後整理"/></label><label className="wide">地址／說明<input placeholder="地址、參與人或參考連結"/></label><button onClick={()=>{setEditing(false);setSaved(true);setTimeout(()=>setSaved(false),2200)}}>儲存到共同行程</button></div>}{saved&&<div className="shared-saved">✓ 已更新共同行程，所有同行者都會看到</div>}{days.map((d,di)=><article className="day-card panel" key={d.date}><div className="day-date"><strong>{d.date}</strong><span>星期{d.day}</span><em>{d.topic}</em></div><div className="timeline">{d.items.map((x,i)=><div className="agenda-row" key={x[0]}><time>{x[0]}</time><i className={`meal-${x[3]}`}></i><div><b>{x[1]}</b><span>{x[2]}</span></div><em>{x[3]}</em>{(i===2||i===3)&&<a href="#">地圖／參考資料 ↗</a>}<button className="row-edit" onClick={()=>setEditing(true)}>編輯</button></div>)}</div><div className="stay"><span>住宿</span><b>⌂ {d.stay}</b><small>{di===0?"入住 06/16 · 退房 06/21":"同前一晚住宿"}</small></div></article>)}</section>}

function MyFlight(){const ref=useRef<HTMLInputElement>(null);return <section className="my-flight"><div><span>我的個人航程</span><h2>Elly 尚未完成回程資料</h2><p>每位同行者只需要登記自己的進出時間，可以手動填寫，也可以直接讓系統讀機票。</p></div><div><button>手動登記航班</button><button className="ticket-upload" onClick={()=>ref.current?.click()}>↑ 上傳我的機票圖片／PDF</button><input ref={ref} type="file" accept="image/*,.pdf" hidden/></div></section>}

function CreateTrip({onCreate}:{onCreate:()=>void}){return <section className="create-shell"><div className="create-copy"><span>新的出差</span><h1>先開一趟行程，<br/>再邀請大家加入。</h1><p>只需要設定共同範圍。每位同行者加入後，再登記自己的進程、回程與航班。</p><ol><li><i>1</i><b>建立出差</b><small>名稱、日期範圍、國家與城市</small></li><li><i>2</i><b>邀請同行者</b><small>每人有自己的登入與行程</small></li><li><i>3</i><b>各自登記機票</b><small>手動填寫或上傳機票辨識</small></li></ol></div><div className="create-card panel"><div><span>步驟 1 / 3</span><h2>建立新出差</h2><p>之後都可以再修改，不需要一次填完。</p></div><label>出差名稱<input defaultValue="法國・波蘭客戶拜訪"/></label><div className="form-row"><label>開始日期<input type="date" defaultValue="2026-06-15"/></label><label>結束日期<input type="date" defaultValue="2026-06-26"/></label></div><div className="form-row"><label>國家<select defaultValue="法國"><option>法國</option><option>波蘭</option><option>美國</option><option>日本</option></select></label><label>城市<select><option>巴黎 Paris</option><option>華沙 Warsaw</option></select></label></div><button className="add-destination">＋ 新增另一個國家／城市</button><button className="create-primary" onClick={onCreate}>建立出差並邀請同行者 →</button><small className="privacy">行程可共用；每個人的機票、單據與報帳仍各自管理。</small></div></section>}

function Itinerary({onInvite,onContinue}:{onInvite:()=>void;onContinue:()=>void}){return <section className="itinerary-shell"><div className="flow"><div className="active"><i>1</i><span><b>共同規劃行程</b><small>現在</small></span></div><em></em><div><i>2</i><span><b>出差申請單</b><small>行程確認後產生</small></span></div><em></em><div><i>3</i><span><b>單據與報支</b><small>出發後使用</small></span></div></div><div className="itinerary-head"><div><span className="live">行前協作</span><h1>先把大家的行程對齊</h1><p>同行者共同確認交通、住宿與拜訪安排；確認完成後，系統自動帶入出差申請單。</p></div><button onClick={onInvite}>＋ 邀請同行者</button></div><div className="itinerary-grid"><section className="panel schedule"><div className="schedule-top"><div><h2>法國・波蘭客戶拜訪</h2><p>2026/06/15–06/26 · 12 天</p></div><div className="avatars"><i>EC</i><i>AL</i><i>KC</i><i>YC</i></div></div>{[["06/15","台北 → 巴黎","長榮航空 BR087","11:20 起飛 · 06:55 抵達"],["06/16–20","巴黎 Paris","產創計畫、法國合作方會議","Hôtel Le Six"],["06/21","巴黎 → 華沙","LOT Polish Airlines LO336","13:10 起飛 · 15:35 抵達"],["06/21–24","華沙 Warsaw","展會與潛在客戶拜訪","Polonia Palace"],["06/25","巴黎 → 台北","長榮航空 BR088","11:20 起飛"]].map((x,i)=><article className="schedule-row" key={x[0]}><div className="date">{x[0]}</div><span className={`type t${i}`}>{i===0||i===2||i===4?"✈":"●"}</span><div><h3>{x[1]}</h3><p>{x[2]}</p><small>{x[3]}</small></div><button>編輯</button></article>)}<button className="add-plan">＋ 新增交通、住宿或拜訪行程</button></section><aside className="precheck"><div className="panel ready"><span>行程完整度</span><strong>90%</strong><i><em></em></i><ul><li>✓ 國家與城市</li><li>✓ 來回交通</li><li>✓ 住宿安排</li><li className="wait">! 1 位同行者尚未確認</li></ul></div><div className="panel generate"><span>下一步</span><h2>行程確認後，自動產生出差申請單</h2><p>日期、國家、城市、交通、住宿與同行者會直接帶入，不必重填。</p><button onClick={onContinue}>確認行程並產生出差單 →</button></div></aside></div></section>}

function Plan(){const rows=[["P0","旅行模式：一鍵拍照／上傳","出差中零填寫；國家→城市自動帶入","已完成"],["P0","例外優先確認匣","只顯示低信心、缺件與超規項目","已完成"],["P0","多人登入與行程分享","共同整理／僅查看；保留上傳者與付款人","已完成原型"],["P0","信用卡帳單自動配對","日期＋店家＋外幣＋卡末四碼；手續費拆列","下一階段"],["P1","Email／訊息收據入口","轉寄訂房信、電子票券即自動歸檔","下一階段"],["P1","住宿明細自動拆項","房費、早餐、住宿稅、洗衣分開處理","下一階段"],["P1","公司規則即時檢核","餐費上限、日期地點、交際對象、重複報帳","規則盤點"],["P2","公司報帳系統串接","輸出報支表、附件 ZIP 或直接送件","待 API"]];return <section className="panel roadmap"><div className="panel-title"><div><h2>競品研究後的改善規劃</h2><p>原則：減少輸入、預設自動、只讓人處理例外</p></div></div><table><thead><tr><th>優先</th><th>改善項目</th><th>使用者價值</th><th>狀態</th></tr></thead><tbody>{rows.map(r=><tr key={r[1]}>{r.map((x,i)=><td key={x} className={i===0?"priority":""}>{x}</td>)}</tr>)}</tbody></table></section>}
