"use client";

import { useEffect, useRef, useState, type ChangeEvent } from "react";

export default function PersistentTravelDocuments(){
 const ref=useRef<HTMLInputElement>(null); const [kind,setKind]=useState<"機票"|"住宿"|null>(null); const [step,setStep]=useState<"reading"|"confirm"|"saving"|"done">("reading"); const [stored,setStored]=useState(0); const [online,setOnline]=useState(false);
 useEffect(()=>{fetch("/api/my-travel").then(x=>x.ok?x.json():null).then(x=>{if(x){setStored(x.documents?.length??0);setOnline(true)}}).catch(()=>{})},[]);
 const start=(type:"機票"|"住宿")=>{setKind(type);setStep("reading");setTimeout(()=>ref.current?.click(),0)};
 const picked=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const body=new FormData();body.append("file",file);body.append("documentType",kind==="機票"?"flight":"stay");await fetch("/api/documents",{method:"POST",body}).catch(()=>null);setStep("confirm")};
 const confirm=async()=>{if(!kind)return;setStep("saving");const flight=kind==="機票";const response=await fetch("/api/my-travel",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:flight?"flight":"stay",title:flight?"BR087・台北 → 巴黎":"Numa Paris Champs-Élysées",travelerName:"Elly Cheng",startAt:flight?"2026-06-15T23:30:00+08:00":"2026-06-16T15:00:00+02:00",endAt:flight?"2026-06-16T08:05:00+02:00":"2026-06-21T11:00:00+02:00",amountMinor:flight?8683700:62400,currency:flight?"TWD":"EUR",cardLast4:"6072",shareSummary:true,createExpense:true})}).catch(()=>null);if(response?.ok){setStored(v=>v+1);setOnline(true)}setStep("done");setTimeout(()=>setKind(null),1800)};
 const people=[["EC","Elly","BR087 台北 → 巴黎","Numa Paris Champs-Élysées"],["AL","Alan","BR087 台北 → 巴黎","Novotel Paris Centre"],["KC","Karen","06/16 AF557 香港 → 巴黎","Numa Paris Champs-Élysées"],["YC","Yoko","06/16 AF557 香港 → 巴黎","Mercure Paris Centre"]];
 return <section className="docs-shell"><div className="docs-head"><div><span>個人交通與住宿</span><h2>每個人可以住不同地方</h2><p>每位同行者登入後只維護自己的安排；分享頁只顯示必要摘要。</p></div><div className="sync-badge">{online?`✓ 已永久保存 ${stored} 份`:`○ 登入後自動永久保存`}・同步行程與我的報支</div></div><div className="docs-grid">{people.map((x,i)=><article className={`person-doc panel ${i===0?"mine":""}`} key={x[1]}><div className="person-name"><i>{x[0]}</i><span><b>{x[1]}</b><small>{i===0?"我的個人安排":"共享摘要"}</small></span>{i===0?<em>只有我可改</em>:<em className="summary-only">僅顯示摘要</em>}</div><div className="doc-line"><span>✈ 機票</span><b>{x[2]}</b>{i===0?<button onClick={()=>start("機票")}>上傳機票</button>:<small>票價與付款不公開</small>}</div><div className="doc-line"><span>⌂ 住宿</span><b>{x[3]}</b>{i===0?<button onClick={()=>start("住宿")}>上傳住宿</button>:<small>房價與附件不公開</small>}</div></article>)}</div><input ref={ref} type="file" accept="image/*,.pdf" hidden onChange={picked}/>{kind&&<div className="travel-overlay"><div className="travel-dialog panel"><button className="x" onClick={()=>setKind(null)}>×</button>{step==="reading"||step==="saving"?<div className="reading"><i></i><h3>{step==="reading"?`正在讀取${kind}…`:"正在永久保存…"}</h3><p>{step==="reading"?"完成後只需確認重要欄位。":"資料依登入者隔離，私人金額不會分享。"}</p></div>:step==="confirm"?<><span className="recognize">AI 辨識結果・請確認</span><h2>{kind==="機票"?"BR087・台北 → 巴黎":"Numa Paris Champs-Élysées"}</h2><div className="recognized-fields">{(kind==="機票"?[["旅客","Elly Cheng"],["出發","2026/06/15 23:30・桃園 TPE"],["抵達","2026/06/16 08:05・巴黎 CDG"],["金額","TWD 86,837・個人卡 •6072"]]:[["住客","Elly Cheng"],["入住","2026/06/16"],["退房","2026/06/21"],["金額","EUR 624.00・個人卡 •6072"]]).map(x=><label key={x[0]}><span>{x[0]}</span><input defaultValue={x[1]}/></label>)}</div><label className="dual-check"><input type="checkbox" defaultChecked/><span><b>加入我的行程</b><small>同行者只看必要摘要</small></span></label><label className="dual-check"><input type="checkbox" defaultChecked/><span><b>建立我的待報支</b><small>金額與卡片只有本人和授權財務可見</small></span></label><button className="confirm-travel" onClick={confirm}>確認並永久保存</button></>:<div className="reading done"><strong>✓</strong><h3>已永久保存</h3><p>{kind}已加入個人行程與個人待報支。</p></div>}</div></div>}</section>
}
