"use client";
import {useEffect,useState} from "react";
import {DEFAULT_CLAIM_TYPES,DEFAULT_CURRENCIES,DEFAULT_DESTINATIONS} from "./managed-config";
import {airportsForManagedCity} from "./airport-directory";

type Account={displayName:string;email:string;notificationEmail?:string;authenticated:boolean;role?:"admin"|"member"|"finance"|"viewer"|null};
type SavedProfile={displayName:string;notificationEmail:string};
type Role="admin"|"member"|"finance"|"viewer";
type LoginUser={displayName:string;email:string;role:Role};
const roles:Role[]=["admin","member","finance","viewer"],roleLabels:Record<Role,string>={admin:"管理者",member:"一般使用者",finance:"財務",viewer:"唯讀"};
const roleNotes:Record<Role,string>={
 admin:"管理登入人員與角色、查看固定主檔；不會自動取得個人報帳內容。",
 member:"建立／加入出差、編輯共同行程，並處理自己的機票、住宿與報帳。",
 finance:"審核與匯出報支、查看審核所需附件；不可代替本人修改私人行程。",
 viewer:"只查看共同行程；不可編輯，也看不到個人報帳。"
};
export default function SystemManagement({account,onClose,mode,onProfileSaved}:{account:Account;onClose:()=>void;mode:"personal"|"admin";onProfileSaved?:(profile:SavedProfile)=>void}){
 const [tab,setTab]=useState<"users"|"claim"|"location"|"currency">("users"),[displayName,setDisplayName]=useState(account.displayName),[notificationEmail,setNotificationEmail]=useState(account.notificationEmail??account.email),[profileMessage,setProfileMessage]=useState(""),[users,setUsers]=useState<LoginUser[]>([]),[newEmail,setNewEmail]=useState(""),[userMessage,setUserMessage]=useState("");
 const loadUsers=async()=>{const r=await fetch("/api/admin/users");if(r.ok)setUsers((await r.json()).users??[]);else setUserMessage(r.status===403?"只有管理者可以管理登入人員":"無法載入登入人員")};
 useEffect(()=>{if(mode!=="admin")return;let active=true;fetch("/api/admin/users").then(async r=>{if(!active)return;if(r.ok)setUsers((await r.json()).users??[]);else setUserMessage(r.status===403?"只有管理者可以管理登入人員":"無法載入登入人員")}).catch(()=>{if(active)setUserMessage("無法載入登入人員")});return()=>{active=false}},[mode]);
 const addUser=async()=>{const email=newEmail.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||users.some(x=>x.email===email))return;const r=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,role:"member"})});if(r.ok){setNewEmail("");await loadUsers()}else setUserMessage("無法加入此人員")};
 const setRole=async(email:string,role:Role)=>{const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({email,role})});if(r.ok)await loadUsers();else setUserMessage(r.status===409?"系統至少需要一位管理者":"無法變更角色")};
 const removeUser=async(email:string)=>{if(!window.confirm(`確定移除 ${email} 的登入權限？`))return;const r=await fetch(`/api/admin/users?email=${encodeURIComponent(email)}`,{method:"DELETE"});if(r.ok)await loadUsers();else setUserMessage(r.status===409?"不能移除目前登入者或最後一位管理者":"無法移除此人員")};
 const saveProfile=async()=>{setProfileMessage("正在保存…");const r=await fetch("/api/me",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({displayName,notificationEmail})});if(r.ok){const saved=await r.json();setProfileMessage("✓ 個人資料已保存");onProfileSaved?.(saved)}else setProfileMessage("請確認姓名與通知 Email")};
 return <div className="management-overlay" onClick={onClose}><section className="management panel" onClick={e=>e.stopPropagation()}><header><div><span>{mode==="personal"?"個人":"系統管理"}</span><h1>{mode==="personal"?"我的個人資料":"項目功能管理"}</h1><p>{mode==="personal"?"編輯本人資料與接收提醒的 Email。":"登入後自動建立一般使用者；管理者可調整角色或停用人員。"}</p></div><button onClick={onClose}>×</button></header>
 {mode==="personal"?<div className="management-body management-login"><article><i>{displayName.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</i><div><b>{displayName}</b><span>{account.email}</span><small>{account.authenticated?"ChatGPT 登入 Email・不可修改":"示範帳號"}</small></div></article><form className="profile-form" onSubmit={e=>{e.preventDefault();saveProfile()}}><label>顯示名稱<input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>通知 Email<input type="email" value={notificationEmail} onChange={e=>setNotificationEmail(e.target.value)} placeholder="接收缺件與行前提醒"/></label><label>登入 Email<input value={account.email} disabled/><small>用於登入與個人資料隔離，不能在此修改。</small></label><button>保存個人資料</button>{profileMessage&&<strong>{profileMessage}</strong>}</form><div className="management-note"><b>個人資料與隱私</b><p>通知 Email 只用於接收行前、缺件及報帳提醒；登入 Email 仍是資料歸屬依據。</p></div></div>:<><nav>{[["users","登入人員"],["claim","報支項目"],["location","國家／城市"],["currency","報支幣別"]].map(([id,label])=><button key={id} className={tab===id?"on":""} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</nav><div className="management-body">
 {tab==="users"?<div className="management-list"><div className="management-note"><b>直接登入即可</b><p>首次登入會自動成為一般使用者，名稱取 Email 的 @ 前面；此處可提前加入、改角色或停用。</p></div><div className="management-add"><input type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addUser()} placeholder="輸入要提前加入的 Email"/><button onClick={addUser}>＋ 提前加入</button></div><div className="role-guide">{roles.map(role=><article key={role}><b>{roleLabels[role]}</b><span>{roleNotes[role]}</span></article>)}</div>{userMessage&&<strong>{userMessage}</strong>}{users.map(user=><article className="login-user-row" key={user.email}><div><b>{user.displayName}</b><small>{user.email}</small></div><select value={user.role} onChange={e=>setRole(user.email,e.target.value as Role)}>{roles.map(role=><option key={role} value={role}>{roleLabels[role]}</option>)}</select><button disabled={user.email===account.email} onClick={()=>removeUser(user.email)}>{user.email===account.email?"目前登入":"移除"}</button></article>)}</div>:tab==="claim"?<div className="master-list"><div className="management-note"><b>公司固定報支項目</b><p>此清單不能新增或刪除。</p></div>{DEFAULT_CLAIM_TYPES.map(x=><span key={x}>{x}</span>)}</div>:tab==="location"?<div className="location-master"><div className="management-note"><b>國家、城市與機場連動主檔</b><p>建立出差時先選國家與城市；上傳機票時會以同一主檔辨識 IATA、機場全名及別名。</p></div><table><thead><tr><th>國家／地區</th><th>城市與機場</th></tr></thead><tbody>{Object.entries(DEFAULT_DESTINATIONS).map(([country,cities])=><tr key={country}><th>{country}</th><td>{cities.map(city=>{const airports=airportsForManagedCity(country,city);return <span key={city}>{city}<small>{airports.length?airports.map(x=>x.code).filter((x,i,a)=>a.indexOf(x)===i).join("、"):"無定期航班機場"}</small></span>})}</td></tr>)}</tbody></table></div>:<div className="management-currency"><div className="management-note"><b>固定申報幣別</b><p>其他幣別會提醒只能用 TWD 申報；信用卡帳單與刷卡資料亦以 TWD 處理。此清單不能新增或刪除。</p></div><div>{DEFAULT_CURRENCIES.map(([code,name])=><span key={code}><b>{code}</b>{name}</span>)}</div></div>}</div></>}
 </section></div>;
}
