"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {prepareImageForUpload,recognizeDocumentText} from "./client-document-processing";

const labels={flight:"機票",stay:"住宿",travel_request:"出差單",internet:"網路"} as const;
type ItemKey=keyof typeof labels;
type TodoValue={checked:boolean;source:"system"|"manual"|null;managed?:boolean};
type Member={userEmail:string;role:string;items:Record<ItemKey,TodoValue>};
type FlightSegment={title:string;startAt:string;endAt:string;origin:string;destination:string;duration?:string|null};
const empty={title:"",startAt:"",endAt:"",origin:"",destination:"",amount:"",currency:"TWD"};
const blankLeg=(title="")=>({title,startAt:"",endAt:"",origin:"",destination:"",duration:null});
const isManagedTravelTodo=(key:ItemKey)=>key==="flight"||key==="stay";

export default function TripTodoPanel({tripId,onBookingSaved}:{tripId:string;onBookingSaved?:()=>void}){
 const [members,setMembers]=useState<Member[]>([]),[me,setMe]=useState(""),[saving,setSaving]=useState<ItemKey|null>(null);
 const [kind,setKind]=useState<"flight"|"stay"|null>(null),[busy,setBusy]=useState(false),[analyzing,setAnalyzing]=useState(false),[notice,setNotice]=useState(""),[form,setForm]=useState(empty),[segments,setSegments]=useState<FlightSegment[]>([]),[file,setFile]=useState<File|null>(null),[documentId,setDocumentId]=useState<string>();const fileRef=useRef<HTMLInputElement>(null);
 const loadTodos=useCallback(async()=>{try{const r=await fetch(`/api/trips/${tripId}/todos`);if(!r.ok)return;const x=await r.json();setMembers(x.members??[]);setMe(x.currentUserEmail??"")}catch{}},[tripId]);
 useEffect(()=>{void loadTodos();const reload=()=>void loadTodos();window.addEventListener("tripclaim:data-changed",reload);return()=>window.removeEventListener("tripclaim:data-changed",reload)},[loadTodos]);
 const toggle=async(key:ItemKey,checked:boolean)=>{if(isManagedTravelTodo(key))return;const before=members.find(m=>m.userEmail===me)?.items[key];setMembers(v=>v.map(m=>m.userEmail===me?{...m,items:{...m.items,[key]:{checked,source:"manual",managed:false}}}:m));setSaving(key);const r=await fetch(`/api/trips/${tripId}/todos`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({itemKey:key,checked})});if(!r.ok&&before)setMembers(v=>v.map(m=>m.userEmail===me?{...m,items:{...m.items,[key]:before}}:m));setSaving(null)};
 const discardDraft=async(id?:string)=>{if(!id)return true;try{const r=await fetch(`/api/documents/${id}?discard=1`,{method:"DELETE"});return r.ok||r.status===404||r.status===409}catch{return false}};
 const closeDraft=async()=>{if(busy||analyzing)return;const current=documentId;if(current&&!await discardDraft(current)){setNotice("無法清除未同步文件，請重試");return}setDocumentId(undefined);setFile(null);setKind(null);setNotice("")};
 const open=(next:"flight"|"stay")=>{setKind(next);setForm(empty);setSegments(next==="flight"?[blankLeg(),blankLeg()]:[]);setFile(null);setDocumentId(undefined);setNotice("")};
 const readFile=async(next:File|null)=>{if(!next||!kind)return;if(documentId){if(!await discardDraft(documentId)){setNotice("上一份未同步文件無法清除，請先重試或取消");return}setDocumentId(undefined)}setFile(next);setAnalyzing(true);setNotice(next.type==="application/pdf"?"正在讀取 PDF 文字與行程資料…":"正在整理並辨識圖片…");try{const prepared=await prepareImageForUpload(next),ocrText=await recognizeDocumentText(prepared.file),body=new FormData();body.append("file",prepared.file,next.name);body.append("tripId",tripId);body.append("documentType",kind);if(ocrText)body.append("ocrText",ocrText);const upload=await fetch("/api/documents",{method:"POST",body});const result=await upload.json().catch(()=>null);if(!upload.ok){setFile(null);setDocumentId(undefined);setNotice(result?.message||"文件讀取失敗，請確認網路後重新上傳");return}if(!result?.id){setFile(null);setDocumentId(undefined);setNotice(result?.queued?"機票／住宿需在線完成上傳；恢復網路後請重新上傳文件。":"未取得文件識別碼，請重新上傳文件。");return}setDocumentId(result.id);const p=result.prefill??{};if(kind==="flight"){const parsed=Array.isArray(p.segments)?p.segments as FlightSegment[]:[];const first={title:p.title||"",startAt:p.startAt||"",endAt:p.endAt||"",origin:p.origin||"",destination:p.destination||"",duration:null};setSegments(parsed.length>=2?parsed:parsed.length===1?[parsed[0],blankLeg()]:[first,blankLeg()])}else setSegments([]);setForm(v=>({...v,title:p.title||v.title,startAt:p.startAt||v.startAt,endAt:p.endAt||v.endAt,origin:p.origin||v.origin,destination:p.destination||v.destination,amount:p.amount||v.amount,currency:p.currency||v.currency}));const missing=[!p.startAt||!p.endAt?"時間":null,!p.amount?"金額":null,...prepared.warnings].filter(Boolean);const legText=kind==="flight"&&p.segments?.length?`，讀到 ${p.segments.length} 個航段`:"";setNotice(missing.length?`上傳成功${legText}；請確認${missing.join("、")}`:`上傳成功${legText}，請確認後同步`)}catch{setFile(null);setDocumentId(undefined);setNotice("自動辨識未完成，請確認網路後重新上傳")}finally{setAnalyzing(false)}};
 const changeSegment=(index:number,key:keyof FlightSegment,value:string)=>setSegments(v=>v.map((segment,i)=>i===index?{...segment,[key]:value}:segment));
 const removeSegment=(index:number)=>setSegments(v=>v.filter((_,i)=>i!==index));
 const duration=(segment:FlightSegment)=>{if(!segment.startAt||!segment.endAt)return "飛行時間待確認";const minutes=Math.round((new Date(segment.endAt).getTime()-new Date(segment.startAt).getTime())/60000);if(minutes<=0)return "請確認抵達時間";return `飛行 ${Math.floor(minutes/60)} 小時${minutes%60?` ${minutes%60} 分`:""}`};
 const saveBooking=async()=>{if(!kind||!form.amount){setNotice("請確認金額");return}const legs:FlightSegment[]=kind==="flight"?segments:[{title:form.title,startAt:form.startAt,endAt:form.endAt,origin:form.origin,destination:form.destination}];const invalid=kind==="flight"?legs.some(leg=>!leg.title||!leg.startAt||!leg.endAt||!leg.origin||!leg.destination):legs.some(leg=>!leg.title||!leg.startAt||!leg.endAt);if(!legs.length||invalid){setNotice(kind==="flight"?"請確認每段航程的航班、出發／抵達時間與機場":"請確認飯店名稱、入住時間與退房時間");return}setBusy(true);const bookedAt=new Date().toISOString(),r=await fetch(`/api/trips/${tripId}/bookings/replace`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,legs,amountMinor:Math.round(Number(form.amount)*100),currency:form.currency,documentId,bookedAt})});if(!r.ok){setBusy(false);setNotice("同步失敗，舊訂單未被前端重用；請重新確認資料");return}const result=await r.json();const key=kind==="flight"?"flight":"stay";setDocumentId(undefined);setBusy(false);setMembers(v=>v.map(m=>m.userEmail===me?{...m,items:{...m.items,[key]:{checked:true,source:"system",managed:true}}}:m));setNotice(`已取代 ${result.replacedOrders??0} 張舊訂單，並同步 ${result.bookingsCreated??legs.length} 段新行程`);window.dispatchEvent(new Event("tripclaim:data-changed"));setTimeout(()=>{setKind(null);setFile(null);onBookingSaved?.()},650)};
 return <aside className="trip-todo-panel panel">
  <header><span>每人自行完成</span><h2>我的行前資料</h2><p>從這裡加入自己的資料，直接同步行程。</p></header>
  <div className="side-booking-actions"><button onClick={()=>open("flight")}>＋ 上傳／登記機票</button><button onClick={()=>open("stay")}>＋ 上傳／登記住宿</button></div>
  <div className="todo-members">{members.map(member=>{const mine=member.userEmail===me,done=Object.values(member.items).filter(item=>item.checked).length;return <section className={mine?"mine":""} key={member.userEmail}><div className="todo-person"><div><b>{mine?"我的待辦":member.userEmail.split("@")[0]}</b><small>{mine?member.userEmail:"僅供查看"}</small></div><strong>{done}/4</strong></div><div className="todo-checks">{(Object.keys(labels) as ItemKey[]).map(key=>{const item=member.items[key],managed=Boolean(item.managed)||isManagedTravelTodo(key);return <label key={key} className={item.checked?"checked":""}><input type="checkbox" checked={item.checked} disabled={!mine||saving===key||managed} onChange={e=>toggle(key,e.target.checked)}/><span>{labels[key]}{mine&&managed?<small>訂單同步</small>:mine&&item.source==="system"?<small>自動</small>:null}</span></label>})}</div></section>})}</div>
  {kind&&typeof document!=="undefined"&&createPortal(<div className="quick-booking-overlay" onClick={()=>void closeDraft()}><section className="quick-booking-dialog panel" role="dialog" aria-modal="true" aria-labelledby="booking-dialog-title" onClick={e=>e.stopPropagation()}>
   <header className="quick-booking-header"><div><span>我的{kind==="flight"?"機票":"住宿"}</span><h2 id="booking-dialog-title">上傳並確認</h2><p>系統先讀取文件，只需確認辨識不確定的欄位。</p></div><button className="dialog-x" aria-label="關閉" disabled={busy||analyzing} onClick={()=>void closeDraft()}>×</button></header>
   <div className="quick-booking-body"><button className={`quick-file ${analyzing?"reading":""}`} disabled={analyzing||busy} onClick={()=>fileRef.current?.click()}>↑ {analyzing?"正在讀取文件…":file?file.name:"上傳機票／訂房文件"}</button><input ref={fileRef} hidden type="file" accept="image/*,.pdf,.heic,.heif" onChange={e=>readFile(e.target.files?.[0]??null)}/>{notice&&<strong className="quick-booking-notice">{notice}</strong>}{kind==="flight"?<div className="flight-segments">{segments.map((segment,index)=><section key={`leg-${index}`}><header><b>{index===0?"去程":index===segments.length-1?"回程":`第 ${index+1} 段`}</b><span>{segment.duration?`飛行 ${segment.duration}`:duration(segment)}</span>{segments.length>2&&<button type="button" onClick={()=>removeSegment(index)}>移除此段</button>}</header><label>航班<input value={segment.title} placeholder={index===0?"例如 BR87":"例如 BR88"} onChange={e=>changeSegment(index,"title",e.target.value)}/></label><div className="flight-route-block"><label>出發機場<input value={segment.origin} placeholder="TPE" onChange={e=>changeSegment(index,"origin",e.target.value.toUpperCase())}/></label><label>出發時間<input type="datetime-local" value={segment.startAt} onChange={e=>changeSegment(index,"startAt",e.target.value)}/></label><i>→</i><label>抵達機場<input value={segment.destination} placeholder="CDG" onChange={e=>changeSegment(index,"destination",e.target.value.toUpperCase())}/></label><label>抵達時間<input type="datetime-local" value={segment.endAt} onChange={e=>changeSegment(index,"endAt",e.target.value)}/></label></div></section>)}<button type="button" className="add-flight-segment" onClick={()=>setSegments(v=>[...v.slice(0,-1),blankLeg(),v.at(-1)??blankLeg()])}>＋ 新增轉機航段</button></div>:<div className="quick-booking-fields"><label>名稱<input value={form.title} placeholder="飯店名稱" onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>入住時間<input type="datetime-local" value={form.startAt} onChange={e=>setForm(v=>({...v,startAt:e.target.value}))}/></label><label>退房時間<input type="datetime-local" value={form.endAt} onChange={e=>setForm(v=>({...v,endAt:e.target.value}))}/></label><label>城市（選填）<input value={form.origin} onChange={e=>setForm(v=>({...v,origin:e.target.value}))}/></label><label>飯店地址（選填）<input value={form.destination} onChange={e=>setForm(v=>({...v,destination:e.target.value}))}/></label></div>}<div className="ticket-amount"><label>整張訂單金額<div><input type="number" min="0" value={form.amount} onChange={e=>setForm(v=>({...v,amount:e.target.value}))}/><input className="currency" value={form.currency} maxLength={3} onChange={e=>setForm(v=>({...v,currency:e.target.value.toUpperCase()}))}/></div></label><small>{kind==="flight"?"來回／多航段只建立一筆本人報支，不重複計價。":"住宿訂單只建立一筆本人報支；入住與退房直接同步行程。"}</small></div></div>
   <footer className="quick-booking-footer"><button className="quick-booking-cancel" disabled={busy||analyzing} onClick={()=>void closeDraft()}>取消</button><button className="quick-booking-save" disabled={busy||analyzing} onClick={saveBooking}>{busy?"正在同步…":"確認並同步"}</button></footer>
  </section></div>,document.body)}
 </aside>
}
