import {NextResponse} from "next/server";
import {and,eq} from "drizzle-orm";
import {getChatGPTUser} from "../../../../chatgpt-auth";
import {getDb} from "../../../../../db";
import {recordAudit,requireTripMember} from "../../../../../db/access";
import {agendaItems,personalExpenses,travelBookings,uploadedDocuments} from "../../../../../db/schema";

export async function POST(_request:Request,{params}:{params:Promise<{kind:string;id:string}>}){
 const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"authentication_required"},{status:401});const {kind,id}=await params,db=await getDb(),now=new Date().toISOString();
 if(!["document","expense","booking"].includes(kind))return NextResponse.json({error:"invalid_kind"},{status:400});let tripId="",documentId:string|null=null,bookingIds:string[]=[];
 if(kind==="document"){const [item]=await db.select().from(uploadedDocuments).where(and(eq(uploadedDocuments.id,id),eq(uploadedDocuments.ownerEmail,user.email))).limit(1);if(!item)return NextResponse.json({error:"not_found"},{status:404});tripId=item.tripId;documentId=item.id;bookingIds=(await db.select({id:travelBookings.id}).from(travelBookings).where(and(eq(travelBookings.documentId,id),eq(travelBookings.ownerEmail,user.email),eq(travelBookings.tripId,tripId)))).map(x=>x.id)}
 if(kind==="expense"){const [item]=await db.select().from(personalExpenses).where(and(eq(personalExpenses.id,id),eq(personalExpenses.ownerEmail,user.email))).limit(1);if(!item)return NextResponse.json({error:"not_found"},{status:404});tripId=item.tripId;documentId=item.sourceDocumentId;bookingIds=item.sourceBookingId?[item.sourceBookingId]:documentId?(await db.select({id:travelBookings.id}).from(travelBookings).where(and(eq(travelBookings.documentId,documentId),eq(travelBookings.ownerEmail,user.email),eq(travelBookings.tripId,tripId)))).map(x=>x.id):[]}
 if(kind==="booking"){const [item]=await db.select().from(travelBookings).where(and(eq(travelBookings.id,id),eq(travelBookings.ownerEmail,user.email))).limit(1);if(!item)return NextResponse.json({error:"not_found"},{status:404});tripId=item.tripId;documentId=item.documentId;bookingIds=[item.id]}
 if(!await requireTripMember(tripId,user.email,{write:true}))return NextResponse.json({error:"forbidden"},{status:403});const writes=[];
 if(documentId){writes.push(db.update(uploadedDocuments).set({deletedAt:null,updatedAt:now}).where(and(eq(uploadedDocuments.id,documentId),eq(uploadedDocuments.ownerEmail,user.email))));writes.push(db.update(personalExpenses).set({deletedAt:null,updatedAt:now}).where(and(eq(personalExpenses.sourceDocumentId,documentId),eq(personalExpenses.ownerEmail,user.email))))}else if(kind==="expense")writes.push(db.update(personalExpenses).set({deletedAt:null,updatedAt:now}).where(and(eq(personalExpenses.id,id),eq(personalExpenses.ownerEmail,user.email))));
 for(const bookingId of bookingIds){writes.push(db.update(travelBookings).set({deletedAt:null,updatedAt:now}).where(and(eq(travelBookings.id,bookingId),eq(travelBookings.ownerEmail,user.email))));writes.push(db.update(agendaItems).set({deletedAt:null,updatedAt:now,updatedByEmail:user.email}).where(and(eq(agendaItems.tripId,tripId),eq(agendaItems.notes,`booking:${bookingId}`))));writes.push(db.update(personalExpenses).set({deletedAt:null,updatedAt:now}).where(and(eq(personalExpenses.sourceBookingId,bookingId),eq(personalExpenses.ownerEmail,user.email))))}
 await db.batch(writes);await recordAudit({tripId,actorEmail:user.email,entityType:kind,entityId:id,action:"restore_graph",after:{documentId,bookingIds,restoredAt:now}});return NextResponse.json({restored:true});
}
