import {NextResponse} from "next/server";
import {and,asc,eq} from "drizzle-orm";
import {strToU8,zipSync} from "fflate";
import {getChatGPTUser} from "../../../../chatgpt-auth";
import {getDb} from "../../../../../db";
import {requireTripMember} from "../../../../../db/access";
import {personalExpenses,uploadedDocuments} from "../../../../../db/schema";
import {buildExpenseGroups,originalAmountOf,originalCurrencyOf,reportingAmountOf,reportingCurrencyOf,safeFilePart} from "../../../../expense-export";

const csv=(rows:(string|number)[][])=>"\ufeff"+rows.map(row=>row.map(value=>`"${String(value??"").replaceAll('"','""')}"`).join(",")).join("\r\n");
const xml=(value:unknown)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const col=(n:number)=>{let value="";for(n++;n;n=Math.floor((n-1)/26))value=String.fromCharCode(65+(n-1)%26)+value;return value};
const workbook=(sheets:Array<{name:string;rows:(string|number)[][]}>)=>{const files:Record<string,Uint8Array>={"[Content_Types].xml":strToU8(`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`),"_rels/.rels":strToU8(`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`),"xl/workbook.xml":strToU8(`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((sheet,i)=>`<sheet name="${xml(sheet.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join("")}</sheets></workbook>`),"xl/_rels/workbook.xml.rels":strToU8(`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}</Relationships>`)};sheets.forEach((sheet,index)=>{const rows=sheet.rows.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>`<c r="${col(c)}${r+1}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`).join("")}</row>`).join("");files[`xl/worksheets/sheet${index+1}.xml`]=strToU8(`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows}</sheetData></worksheet>`)});return zipSync(files,{level:6})};

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 const user=await getChatGPTUser(),{id:tripId}=await params;if(!user)return NextResponse.json({error:"authentication_required"},{status:401});
 if(!await requireTripMember(tripId,user.email))return NextResponse.json({error:"forbidden"},{status:403});
 const db=await getDb(),expenses=await db.select().from(personalExpenses).where(and(eq(personalExpenses.tripId,tripId),eq(personalExpenses.ownerEmail,user.email))).orderBy(asc(personalExpenses.expenseDate)),groups=buildExpenseGroups(expenses),documentIds=[...new Set(expenses.map(x=>x.sourceDocumentId).filter(Boolean))] as string[],allDocuments=await db.select().from(uploadedDocuments).where(and(eq(uploadedDocuments.tripId,tripId),eq(uploadedDocuments.ownerEmail,user.email))),documents=documentIds.length?allDocuments.filter(x=>documentIds.includes(x.id)):[],documentsById=new Map(documents.map(x=>[x.id,x])),files:Record<string,Uint8Array>={};
 files["00_旅費報支彙總.csv"]=strToU8(csv([["行次","報支項目","申報幣別","申報總額","費用筆數","憑證數"],...groups.map(g=>[g.rowNumber,g.category,g.currency,(g.amountMinor/100).toFixed(2),g.expenses.length,g.expenses.reduce((sum,x)=>sum+(x.receiptCount||1),0)])]));
 files["00_費用明細.csv"]=strToU8(csv([["行次","日期","報支項目","店家／說明","原始幣別","原始金額","申報幣別","申報金額","憑證數","Remark","費用歸屬","卡末四碼"],...groups.flatMap(g=>g.expenses.map(x=>[g.rowNumber,x.expenseDate,x.category,x.merchant,originalCurrencyOf(x),((originalAmountOf(x))/100).toFixed(2),reportingCurrencyOf(x),((reportingAmountOf(x))/100).toFixed(2),x.receiptCount,x.remark??"",x.costCenter,x.cardLast4??""]))]));
 const manifest:{generatedAt:string;tripId:string;ownerEmail:string;groups:Array<Record<string,unknown>>}={generatedAt:new Date().toISOString(),tripId,ownerEmail:user.email,groups:[]};
 const {env}=await import("cloudflare:workers");
 for(const group of groups){const groupEntry={rowNumber:group.rowNumber,category:group.category,currency:group.currency,amountMinor:group.amountMinor,folder:group.folder,expenses:[] as Array<Record<string,unknown>>};manifest.groups.push(groupEntry);for(const expense of group.expenses){const doc=expense.sourceDocumentId?documentsById.get(expense.sourceDocumentId):null,base=`${expense.expenseDate.replaceAll("-","")}_${safeFilePart(expense.category)}_${safeFilePart(expense.merchant)}_${reportingCurrencyOf(expense)}${(reportingAmountOf(expense)/100).toFixed(2)}`;let attachment:string|null=null;if(doc){const object=await env.BUCKET.get(doc.objectKey);if(object){const extension=doc.originalName.includes(".")?doc.originalName.slice(doc.originalName.lastIndexOf(".")):"",name=`${base}_${safeFilePart(doc.documentType)}${extension}`,path=`${group.folder}/${name}`;files[path]=new Uint8Array(await object.arrayBuffer());attachment=path}}groupEntry.expenses.push({expenseId:expense.id,documentId:expense.sourceDocumentId,originalName:doc?.originalName??null,attachment,originalCurrency:originalCurrencyOf(expense),originalAmountMinor:originalAmountOf(expense),reportingCurrency:reportingCurrencyOf(expense),reportingAmountMinor:reportingAmountOf(expense)})}}
 files["00_附件索引_manifest.json"]=strToU8(JSON.stringify(manifest,null,2));
 const summaryRows:(string|number)[][]=[["行次","報支項目","申報幣別","申報總額","費用筆數","憑證數"],...groups.map(g=>[g.rowNumber,g.category,g.currency,(g.amountMinor/100).toFixed(2),g.expenses.length,g.expenses.reduce((sum,x)=>sum+(x.receiptCount||1),0)])],detailRows:(string|number)[][]=[["行次","日期","報支項目","店家／說明","原始幣別","原始金額","申報幣別","申報金額","憑證數","Remark","費用歸屬","卡末四碼"],...groups.flatMap(g=>g.expenses.map(x=>[g.rowNumber,x.expenseDate,x.category,x.merchant,originalCurrencyOf(x),(originalAmountOf(x)/100).toFixed(2),reportingCurrencyOf(x),(reportingAmountOf(x)/100).toFixed(2),x.receiptCount,x.remark??"",x.costCenter,x.cardLast4??""]))],cardRows:(string|number)[][]=[["文件日期","文件類型","店家／說明","卡末四碼","TWD 實際請款","配對費用 ID","狀態"],...allDocuments.filter(x=>x.documentType.includes("信用卡")||x.documentType.includes("刷卡")||x.claimType==="國外交易手續費").map(x=>[x.expenseDate??"",x.documentType,x.merchant??x.originalName,x.cardLast4??"",x.billedTwdMinor==null?"":(x.billedTwdMinor/100).toFixed(2),x.linkedExpenseId??"",x.linkedExpenseId?"已配對":x.status==="ready"?"已保存、待配對":"待確認"])],missingRows:(string|number)[][]=[["類型","文件／項目","原因","處理狀態"],...allDocuments.filter(x=>x.status!=="ready"||((x.documentType.includes("信用卡")||x.documentType.includes("刷卡"))&&!x.linkedExpenseId)).map(x=>[x.documentType,x.originalName,x.status!=="ready"?"資料尚未確認":"尚未配對本人費用",x.status!=="ready"?"待確認":"缺配對"])],attachmentRows:(string|number)[][]=[["行次","費用 ID","文件 ID","原始檔名","標準附件路徑","原始幣別","原始金額","申報幣別","申報金額"],...manifest.groups.flatMap(group=>(group.expenses as Array<Record<string,unknown>>).map(expense=>[group.rowNumber as number,expense.expenseId as string,expense.documentId as string??"",expense.originalName as string??"",expense.attachment as string??"",expense.originalCurrency as string,((expense.originalAmountMinor as number)/100).toFixed(2),expense.reportingCurrency as string,((expense.reportingAmountMinor as number)/100).toFixed(2)]))],xlsx=workbook([{name:"報支彙總",rows:summaryRows},{name:"費用明細",rows:detailRows},{name:"信用卡與手續費",rows:cardRows},{name:"缺件",rows:missingRows},{name:"附件索引",rows:attachmentRows}]);
 if(new URL(request.url).searchParams.get("format")==="xlsx"){const body=xlsx.buffer.slice(xlsx.byteOffset,xlsx.byteOffset+xlsx.byteLength) as ArrayBuffer;return new Response(body,{headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(`TripClaim_${tripId}.xlsx`)}`,"cache-control":"private, no-store"}})}
 files["00_正式旅費報支.xlsx"]=xlsx;
 const zipped=zipSync(files,{level:6}),body=zipped.buffer.slice(zipped.byteOffset,zipped.byteOffset+zipped.byteLength) as ArrayBuffer;
 return new Response(body,{headers:{"content-type":"application/zip","content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(`TripClaim_${tripId}.zip`)}`,"cache-control":"private, no-store"}});
}
