import {NextRequest,NextResponse} from "next/server";
import {and,eq} from "drizzle-orm";
import {getChatGPTUser} from "../../../../../chatgpt-auth";
import {getDb} from "../../../../../../db";
import {recordAudit,requireTripMember} from "../../../../../../db/access";
import {agendaItems} from "../../../../../../db/schema";

type P={params:Promise<{id:string;itemId:string}>};
export async function PATCH(request:NextRequest,{params}:P){const user=await getChatGPTUser(),{id,itemId}=await params;if(!user)return NextResponse.json({error:"authentication_required"},{status:401});if(!await requireTripMember(id,user.email,{write:true}))return NextResponse.json({error:"forbidden"},{status:403});const input=await request.json() as {version?:number;type?:string;title?:string;startsAt?:string;endsAt?:string;timezone?:string;place?:string;address?:string;referenceUrl?:string;notes?:string};if(!input.version)return NextResponse.json({error:"version_required"},{status:400});const db=await getDb();const [before]=await db.select().from(agendaItems).where(and(eq(agendaItems.id,itemId),eq(agendaItems.tripId,id))).limit(1);if(!before||before.deletedAt)return NextResponse.json({error:"not_found"},{status:404});if(before.version!==input.version)return NextResponse.json({error:"edit_conflict",current:before},{status:409});const next={type:input.type??before.type,title:input.title?.trim()??before.title,startsAt:input.startsAt??before.startsAt,endsAt:input.endsAt??before.endsAt,timezone:input.timezone??before.timezone,place:input.place??before.place,address:input.address??before.address,referenceUrl:input.referenceUrl??before.referenceUrl,notes:input.notes??before.notes,updatedByEmail:user.email,version:before.version+1,updatedAt:new Date().toISOString()};await db.update(agendaItems).set(next).where(and(eq(agendaItems.id,itemId),eq(agendaItems.version,before.version)));await recordAudit({tripId:id,actorEmail:user.email,entityType:"agenda_item",entityId:itemId,action:"update",before,after:next});return NextResponse.json({saved:true,version:next.version})}
export async function DELETE(_:NextRequest,{params}:P){const user=await getChatGPTUser(),{id,itemId}=await params;if(!user)return NextResponse.json({error:"authentication_required"},{status:401});if(!await requireTripMember(id,user.email,{write:true}))return NextResponse.json({error:"forbidden"},{status:403});const db=await getDb();const [before]=await db.select().from(agendaItems).where(and(eq(agendaItems.id,itemId),eq(agendaItems.tripId,id))).limit(1);if(!before||before.deletedAt)return NextResponse.json({error:"not_found"},{status:404});const now=new Date().toISOString();await db.update(agendaItems).set({deletedAt:now,updatedAt:now,updatedByEmail:user.email,version:before.version+1}).where(eq(agendaItems.id,itemId));await recordAudit({tripId:id,actorEmail:user.email,entityType:"agenda_item",entityId:itemId,action:"soft_delete",before});return NextResponse.json({deleted:true,recoverable:true})}
